import { useEffect, useState } from 'react'
import { FileUp, FileText } from 'lucide-react'
import { Button, Card, EmptyState, Badge } from '@/components/kit'
import { supabase } from '@/lib/supabase'

export function RecordsPage(){const[patientId,setPatientId]=useState<string|null>(null);const[records,setRecords]=useState<any[]>([]);const[type,setType]=useState('LAB_REPORT');const[date,setDate]=useState('');const[file,setFile]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
const load=async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user)return;const{data:p}=await supabase.from('patient_profiles').select('id').eq('user_id',user.id).maybeSingle();if(!p)return;setPatientId(p.id);const{data}=await supabase.from('health_records').select('*').eq('patient_id',p.id).order('created_at',{ascending:false});setRecords(data??[])};useEffect(()=>{load()},[])
const upload=async()=>{if(!file||!patientId)return;setBusy(true);setMsg('');const user=(await supabase.auth.getUser()).data.user;if(!user)return;const ext=file.name.split('.').pop()||'bin';const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const{error:u}=await supabase.storage.from('health-records').upload(path,file,{upsert:false});if(u){setMsg(u.message);setBusy(false);return}const{error:d}=await supabase.from('health_records').insert({patient_id:patientId,record_type:type,record_date:date||null,source_type:'PATIENT_UPLOAD',storage_path:path,original_filename:file.name,mime_type:file.type||null,verification_status:'UNVERIFIED'});if(d)setMsg(d.message);else{setMsg('Record uploaded. It is marked Patient Supplied / Unverified until reviewed.');setFile(null);await load()}setBusy(false)}
return <div><h1 className="text-2xl font-bold">Health Records</h1><p className="mt-1 text-sm text-muted-foreground">Upload your real PDF/image records. Files are private; nothing is pre-filled.</p><Card className="mt-6"><div className="flex items-center gap-2"><FileUp className="size-5 text-primary"/><h2 className="font-semibold">Upload health record</h2></div><div className="mt-4 grid gap-3 md:grid-cols-3"><select className="rounded-lg border border-border px-3 py-2" value={type} onChange={e=>setType(e.target.value)}><option value="PRESCRIPTION">Prescription</option><option value="LAB_REPORT">Lab report</option><option value="DISCHARGE_SUMMARY">Discharge summary</option><option value="IMAGING_REPORT">Imaging report</option><option value="VACCINATION_RECORD">Vaccination record</option><option value="OTHER">Other clinical document</option></select><input className="rounded-lg border border-border px-3 py-2" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input className="rounded-lg border border-border px-3 py-2" type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></div><Button className="mt-4" disabled={!file||busy} onClick={upload}>Upload securely</Button>{msg&&<p className="mt-3 text-sm text-muted-foreground">{msg}</p>}</Card><div className="mt-6 space-y-3">{records.length===0?<EmptyState text="No health records uploaded yet."/>:records.map(r=><Card key={r.id} className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><FileText className="size-5 text-primary"/><div><p className="font-semibold">{r.original_filename}</p><p className="text-xs text-muted-foreground">{r.record_type} · {r.record_date??'date not supplied'}</p></div></div><Badge tone={r.verification_status==='VERIFIED'?'success':'warning'}>{r.verification_status}</Badge></Card>)}</div></div>}
