import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`a0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){try{await f();passed++;console.log('PASS '+name)}catch(e){throw Error(name+': '+e.message)}}
await db.exec(`insert into auth.users(id) values('${id(1)}'),('${id(2)}'),('${id(3)}');
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','PROV-A','Fixture A'),('${id(12)}','${id(2)}','PROV-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(13)}','${id(3)}','DOCTOR','Fixture doctor','APPROVED');
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','Source complaint','Original note');`);

async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
let pref,message;
await test('patient contact opt-in remains unverified until trusted verification evidence',async()=>{pref=await as(1,()=>scalar("select c4_preference('EMAIL','fixture@example.invalid',now()+interval '1 day')"));await as(1,()=>assert.rejects(()=>q("select c4_verify_contact($1,'invented')",[pref])));await as(3,()=>assert.rejects(()=>q("select c4_enqueue('APPOINTMENT',$1,'EMAIL',$2)",[id(20),id(30)]),/verified channel/));await service(()=>q("select c4_verify_contact($1,'fixture-confirmation-source')",[pref]))});
await test('only source participants enqueue and retries do not duplicate messages',async()=>{await as(2,()=>assert.rejects(()=>q("select c4_enqueue('APPOINTMENT',$1,'EMAIL',$2)",[id(20),id(30)]),/authorized/));const send=()=>as(3,()=>scalar("select c4_enqueue('APPOINTMENT',$1,'EMAIL',$2)",[id(20),id(30)]));message=await send();assert.equal(await send(),message);assert.equal(await scalar('select state from care_communications where id=$1',[message]),'QUEUED')});
await test('delivery adapter receives generic template with stable key and no clinical content',async()=>{await as(1,()=>assert.rejects(()=>q('select c4_delivery_payload($1)',[message])));const p=await service(()=>scalar('select c4_delivery_payload($1)',[message]));assert.equal(p.idempotency_key,message);assert.equal(p.destination,'fixture@example.invalid');assert.doesNotMatch(JSON.stringify(p),/Source complaint|Original note|patient_id|appointment_id/)});
await test('sent and delivered require actual receipts and do not complete appointment',async()=>{await service(()=>assert.rejects(()=>q("select c4_delivery_event($1,'DELIVERED','fixture-provider','fixture-event','{}')",[message]),/transition/));await service(()=>q("select c4_delivery_event($1,'SENT','fixture-provider','fixture-sent','{}')",[message]));await service(()=>q("select c4_delivery_event($1,'SENT','fixture-provider','fixture-sent','{}')",[message]));await service(()=>q("select c4_delivery_event($1,'DELIVERED','fixture-provider','fixture-delivered','{}')",[message]));assert.equal(await scalar('select status from appointments where id=$1',[id(20)]),'CONFIRMED');assert.equal(await scalar('select count(*)::int from communication_receipts'),2)});
await test('only actual recipient acknowledges and acknowledgement is not care closure',async()=>{await as(3,()=>assert.rejects(()=>q('select c4_acknowledge($1)',[message])));await as(1,()=>q('select c4_acknowledge($1)',[message]));assert.equal((await as(1,()=>scalar('select c4_messages()')))[0].state,'ACKNOWLEDGED');assert.equal((await as(2,()=>scalar('select c4_messages()'))).length,0);assert.equal(await scalar('select status from encounters where id=$1',[id(21)]),'IN_PROGRESS')});
await test('contact revocation cancels queued sends and prevents stale adapter use',async()=>{const m=await as(3,()=>scalar("select c4_enqueue('APPOINTMENT',$1,'EMAIL',$2)",[id(20),id(31)]));await as(1,()=>q('select c4_revoke($1)',[pref]));await service(()=>assert.rejects(()=>q('select c4_delivery_payload($1)',[m]),/revoked/));assert.equal(await scalar('select state from care_communications where id=$1',[m]),'CANCELLED')});
console.log(passed+' communication lifecycle tests passed');await db.close();
