import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);
await test('safe facility context exposes only owned or active memberships',async()=>{const own=(await as(8,()=>q('select * from h1_my_facilities()'))).rows;assert.deepEqual(own.map(f=>f.facility_id),[id(40)]);assert.equal(own[0].role,'OWNER');assert.equal(own[0].operational_access,true);assert.equal((await as(10,()=>q('select * from h1_my_facilities()'))).rows.length,0);await as(8,()=>q("select h1_set_member($1,$2,'RECEPTION',true)",[id(40),id(10)]));const staff=(await as(10,()=>q('select * from h1_my_facilities()'))).rows;assert.equal(staff[0].role,'RECEPTION');assert.equal(staff[0].membership_state,'ACTIVE');assert.equal(staff.length,1)});
await test('revoked membership removes facility context without opening raw RLS tables',async()=>{await as(8,()=>q("select h1_set_member($1,$2,'RECEPTION',false)",[id(40),id(10)]));assert.equal((await as(10,()=>q('select * from h1_my_facilities()'))).rows.length,0);await as(10,()=>assert.rejects(()=>q('select * from facility_memberships')))});
await test('suspended owner retains setup context but no operational authorization',async()=>{await q("update provider_profiles set verification_status='SUSPENDED' where id=$1",[id(18)]);const r=(await as(8,()=>q('select * from h1_my_facilities()'))).rows[0];assert.equal(r.verification_status,'SUSPENDED');assert.equal(r.operational_access,false)});
await test('facility context is bounded, authenticated and works for pharmacy ownership',async()=>{await q("insert into facilities(id,owner_user_id,name,facility_type) values($1,$2,'Pharmacy site','PHARMACY')",[id(90),id(4)]);assert.equal((await as(4,()=>q('select * from h1_my_facilities()'))).rows[0].facility_type,'PHARMACY');await as(4,()=>assert.rejects(()=>q('select * from h1_my_facilities(0,51)')));await db.exec('set role anon');try{await assert.rejects(()=>q('select * from h1_my_facilities()'))}finally{await db.exec('reset role')}});
await test('new operational RPCs grant no anonymous execution and helpers remain internal',async()=>{const leaked=(await q("select proname from pg_proc where pronamespace='public'::regnamespace and proname ~ '^(h[123]|r[12]|p[23]|w1)_' and has_function_privilege('anon',oid,'EXECUTE')")).rows;assert.deepEqual(leaked,[]);for(const name of ['w1_book_for_patient','h1_staff','h1_can_manage','h2_admission_record','r1_no_specimen','p2_stock_change'])assert.equal(await scalar("select has_function_privilege('authenticated',oid,'EXECUTE') from pg_proc where pronamespace='public'::regnamespace and proname=$1",[name]),false)});
console.log(`${passed} frontend backend-contract tests passed`);await db.close();
