import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`b0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){await f();passed++;console.log('PASS '+name)}
await q('insert into auth.users(id) values($1),($2)',[id(1),id(2)]);await q("update profiles set role='ADMIN' where id=$1",[id(1)]);

const rows=['PATHOLOGY','IMAGING','PROCEDURE'].map((category,i)=>({source_code:'fixture-'+i,name:'Synthetic diagnostic '+i,category}));
const imp=(v='v1',r=rows,dry=false,assurance='SOURCE_RECORDED',key=50)=>as(1,()=>scalar('select k2_import($1,$2,$3,$4,current_date,$5,$6,$7)',['Fixture diagnostics',v,'Synthetic test evidence',assurance,JSON.stringify(r),id(key),dry]));
let batch,master;
await test('diagnostic import validates category, missing rules and source provenance',async()=>{assert.equal((await imp('bad',[{...rows[0],category:'OTHER'}],true)).valid,false);assert.equal((await imp('bad',[{...rows[0],reference_rule:'Fabricated rule'}],true,'DEMO')).valid,false);batch=(await imp()).batch_id;assert.equal((await imp()).batch_id,batch);await assert.rejects(()=>imp('v1',[rows[0]]),/conflict/);const r=await as(2,()=>scalar("select k2_diagnostics(p_category=>'PATHOLOGY')"));assert.equal(r.items.length,1);master=r.items[0].id;assert.equal(r.items[0].reference_rule,null);assert.equal(r.items[0].critical_rule,null);assert.equal(r.items[0].source_version,'v1')});
await test('catalog categories and pagination do not imply capability or price',async()=>{for(const c of ['PATHOLOGY','IMAGING','PROCEDURE'])assert.equal((await as(2,()=>scalar('select k2_diagnostics(p_category=>$1)',[c]))).items.length,1);const r=await as(2,()=>scalar('select k2_diagnostics(p_limit=>2)'));assert.equal(r.items.length,2);assert.equal((await as(2,()=>scalar('select k2_diagnostics(p_after=>$1)',[r.next_after]))).items.length,1);assert.equal(r.items[0].price,undefined);assert.equal(await scalar('select count(*)::int from diagnostic_master_bindings'),0)});
await test('binding requires actual classified test and never creates lab capability',async()=>{await q("insert into diagnostic_tests(id,test_code,test_name,workflow_kind) values($1,'FIXTURE','Synthetic local definition','IMAGING')",[id(60)]);await as(1,()=>assert.rejects(()=>q('select k2_bind($1,$2)',[id(60),master]),/matching/));await q("update diagnostic_tests set workflow_kind='PATHOLOGY' where id=$1",[id(60)]);await as(2,()=>assert.rejects(()=>q('select k2_bind($1,$2)',[id(60),master])));await as(1,()=>q('select k2_bind($1,$2)',[id(60),master]));assert.equal(await scalar('select count(*)::int from diagnostic_master_bindings'),1);assert.equal(await scalar('select count(*)::int from lab_test_capabilities'),0)});
await test('new source version and disabled batch preserve old evidence',async()=>{const r=await imp('v2',[{...rows[0],active:false}],false,'SOURCE_RECORDED',51);assert.equal((await as(2,()=>scalar("select k2_diagnostics(p_category=>'PATHOLOGY')"))).items.length,0);await as(1,()=>q("select k1_disable_batch($1,'Withdraw source edition')",[r.batch_id]));assert.equal((await as(2,()=>scalar("select k2_diagnostics(p_category=>'PATHOLOGY')"))).items[0].id,master);assert.equal(await scalar('select count(*)::int from diagnostic_master'),4);await as(2,()=>assert.rejects(()=>q('update diagnostic_master set active=false')))});
console.log(passed+' diagnostic master tests passed');await db.close();
