import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`a0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){try{await f();passed++;console.log('PASS '+name)}catch(e){throw Error(name+': '+e.message)}}
await db.exec(`insert into auth.users(id) values('${id(1)}'),('${id(2)}'),('${id(3)}');
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','PROV-A','Fixture A'),('${id(12)}','${id(2)}','PROV-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(13)}','${id(3)}','DOCTOR','Fixture doctor','APPROVED');
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','Source complaint','Original note');`);
await q("insert into health_records(id,patient_id,record_type,source_type,storage_path,original_filename) values($1,$2,'REPORT','PATIENT_UPLOAD','private-original','Actual original.pdf')",[id(40),id(11)]);
let job,draft;
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
await test('extraction requires own actual private original and never fakes configuration',async()=>{await as(1,()=>assert.rejects(()=>q('select q1_request($1,$2)',[id(40),id(50)]),/Original/));await q("insert into storage.objects(bucket_id,name) values('health-records','private-original')");await as(2,()=>assert.rejects(()=>q('select q1_request($1,$2)',[id(40),id(50)])));job=await as(1,()=>scalar('select q1_request($1,$2)',[id(40),id(50)]));assert.equal(await as(1,()=>scalar('select q1_request($1,$2)',[id(40),id(50)])),job);assert.equal((await as(1,()=>scalar('select q1_read($1)',[job]))).job.state,'CONFIGURATION_REQUIRED')});
await test('patient cannot forge verified upload or call extraction adapter boundary',async()=>{await as(1,()=>assert.rejects(()=>q("insert into health_records(patient_id,record_type,source_type,storage_path,original_filename,verification_status) values($1,'REPORT','PATIENT_UPLOAD','fake','fake.pdf','VERIFIED')",[id(11)])));await as(1,()=>assert.rejects(()=>q("select q1_claim($1,'fake','fake')",[job])));await service(()=>q("select q1_claim($1,'fixture-provider','fixture-model-v1')",[job]))});
const raw='Source document says recorded finding.';const fields={finding:{value:'recorded finding',confidence:0.8,source_quote:'recorded finding'}};
await test('model fields must have confidence and source quotes and remain unverified drafts',async()=>{await service(()=>assert.rejects(()=>q('select q1_extracted($1,$2,$3,$4::jsonb,$5)',[job,'LAB_REPORT',raw,JSON.stringify({finding:{value:'invented',confidence:0.9,source_quote:'not in source'}}),'fixture-event']),/quote/));draft=await service(()=>scalar('select q1_extracted($1,$2,$3,$4::jsonb,$5)',[job,'LAB_REPORT',raw,JSON.stringify(fields),'fixture-event']));assert.equal(await scalar('select verification_status from health_records where id=$1',[id(40)]),'UNVERIFIED');assert.equal(await scalar('select count(*)::int from prescriptions'),0)});
await test('clinical extraction review requires document consent and explicit patient matching',async()=>{await as(3,()=>assert.rejects(()=>q("select q1_review($1,'{}','Actual review note',true,$2)",[draft,id(51)]),/consent/));const c=await as(3,()=>scalar("select a1_request_consent($1,'TREATMENT',array['DOCUMENTS'],'Review uploaded document',now(),now()+interval '1 day')",[id(11)]));await as(1,()=>q("select a1_decide_consent($1,'GRANTED')",[c]));await as(3,()=>assert.rejects(()=>q("select q1_review($1,'{}','Actual review note',false,$2)",[draft,id(51)]),/patient match/))});
await test('corrections are versioned with provenance and never replace original OCR/source authenticity',async()=>{const review=()=>as(3,()=>scalar("select q1_review($1,$2::jsonb,'Clinician reviewed transcription and patient identity',true,$3)",[draft,JSON.stringify({summary:'Corrected transcription'}),id(51)]));assert.equal(await review(),await review());await as(3,()=>q("select q1_review($1,$2::jsonb,'Clinician amended transcription after source check',true,$3)",[draft,JSON.stringify({summary:'Revised transcription'}),id(52)]));const r=await as(1,()=>scalar('select q1_read($1)',[job]));assert.equal(r.reviews.length,2);assert.equal(r.draft.raw_text,raw);assert.equal(r.reviews[0].source_authenticity,'UNKNOWN');assert.equal(await scalar('select verification_status from health_records where id=$1',[id(40)]),'UNVERIFIED');assert.equal(await scalar("select count(*)::int from clinical_source_versions where source_kind='document_extraction_reviews'"),2)});
await test('revocation prevents subsequent model outputs even during processing',async()=>{const j=await as(1,()=>scalar('select q1_request($1,$2)',[id(40),id(53)]));await service(()=>q("select q1_claim($1,'fixture-provider','fixture-model-v1')",[j]));await as(1,()=>q('select q1_cancel($1)',[j]));await service(()=>assert.rejects(()=>q('select q1_extracted($1,$2,$3,$4::jsonb,$5)',[j,'LAB_REPORT',raw,JSON.stringify(fields),'fixture-event-2']),/revoked/));assert.equal(await scalar('select count(*)::int from document_extraction_drafts'),1)});
console.log(`${passed} document intelligence tests passed`);await db.close();
