import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`b0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){await f();passed++;console.log('PASS '+name)}
await q('insert into auth.users(id) values($1),($2)',[id(1),id(2)]);await q("update profiles set role='ADMIN' where id=$1",[id(1)]);

await q('insert into auth.users(id) values($1)',[id(3)]);await q("update profiles set role='ADMIN' where id=$1",[id(3)]);let incident,policy,model;
await test('incident submission is idempotent and reporter isolation is preserved',async()=>{const report=()=>as(2,()=>scalar("select a4_incident('DATA_QUALITY','Actual workflow issue needing review',$1)",[id(10)]));incident=await report();assert.equal(await report(),incident);assert.equal((await as(2,()=>scalar('select a4_incidents()'))).length,1);await as(2,()=>assert.rejects(()=>q("select a4_incident_transition($1,'TRIAGED','MEDIUM',$2,1,'Reviewed actual incident',$3)",[incident,id(1),id(11)])))});
await test('incident changes enforce revisions transitions and exact retry payload',async()=>{const transition=()=>as(1,()=>scalar("select a4_incident_transition($1,'TRIAGED','MEDIUM',$2,1,'Reviewed actual incident',$3)",[incident,id(1),id(11)]));assert.equal(await transition(),2);assert.equal(await transition(),2);await as(1,()=>assert.rejects(()=>q("select a4_incident_transition($1,'TRIAGED','HIGH',$2,1,'Reviewed actual incident',$3)",[incident,id(1),id(11)]),/conflict/));await as(1,()=>assert.rejects(()=>q("select a4_incident_transition($1,'INVESTIGATING','MEDIUM',$2,1,'Stale incident update',$3)",[incident,id(1),id(12)]),/Stale/));await as(1,()=>assert.rejects(()=>q("select a4_incident_transition($1,'CLOSED','MEDIUM',$2,2,'Skip investigation attempt',$3)",[incident,id(1),id(12)]),/transition/))});
await test('retention is immutable metadata with independent approval and no purge',async()=>{policy=await as(1,()=>scalar("select a4_retention('CLINICAL_RECORDS',1,3650,'Actual reviewed organizational retention reference')"));await as(1,()=>assert.rejects(()=>q('select a4_approve_retention($1)',[policy]),/Independent/));await as(3,()=>q('select a4_approve_retention($1)',[policy]));assert.equal(await scalar('select approved_by from retention_policy_versions where id=$1',[policy]),id(3));await as(1,()=>assert.rejects(()=>q("select a4_retention('CLINICAL_RECORDS',1,1,'Changed retention reference')"),/Immutable/));assert.equal(await scalar('select count(*)::int from governance_incidents'),1)});
await test('model suspension immediately blocks evaluated deployed route and stale release',async()=>{model=await as(1,()=>scalar("select m1_register('External fixture','v1','EXTERNAL','FIXTURE',array['SOURCE_SELECTION'],array['English'])"));const scores={English:{cases:20,unsupported_claims:0,unsafe_actions:0,isolation_failures:0,citation_accuracy:1}};const e=await service(()=>scalar('select m1_evaluate($1,$2,$3::jsonb,$4)',[model,'fixture-suite',JSON.stringify(scores),'fixture-source']));await as(1,()=>q("select m1_approve($1,'Reviewed offline evaluation')",[e]));await as(1,()=>q("select m1_deploy('SOURCE_SELECTION','English',$1,0,'Approved fixture route')",[model]));await as(1,()=>q("select a4_model_hold($1,true,0,'Suspend for investigation')",[model]));await service(()=>assert.rejects(()=>q("select m1_route('SOURCE_SELECTION','English')"),/CONFIGURATION/));await as(1,()=>assert.rejects(()=>q("select a4_model_hold($1,false,0,'Stale release request')",[model]),/Stale/));await as(3,()=>q("select a4_model_hold($1,false,1,'Reviewed issue and released hold')",[model]));assert.equal((await service(()=>scalar("select m1_route('SOURCE_SELECTION','English')"))).primary.id,model)});
await test('audit and model history are bounded governance queries without clinical metadata',async()=>{await as(2,()=>assert.rejects(()=>q('select a4_audit()')));const audit=await as(1,()=>scalar('select a4_audit()'));assert.ok(audit.length);assert.equal(audit[0].metadata,undefined);const h=await as(1,()=>scalar('select a4_model_history($1)',[model]));assert.equal(h.evaluations.length,1);assert.equal(h.hold.suspended,false)});
console.log(passed+' governance operations tests passed');await db.close();
