import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`a0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){try{await f();passed++;console.log('PASS '+name)}catch(e){throw Error(name+': '+e.message)}}
await db.exec(`insert into auth.users(id) values('${id(1)}'),('${id(2)}'),('${id(3)}');
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','PROV-A','Fixture A'),('${id(12)}','${id(2)}','PROV-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(13)}','${id(3)}','DOCTOR','Fixture doctor','APPROVED');
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','Source complaint','Original note');`);

await q('insert into auth.users(id) values($1),($2)',[id(4),id(5)]);await q("update profiles set role='ADMIN' where id=$1",[id(4)]);
let candidate;
const propose=(key=50)=>as(4,()=>scalar("select x1_propose($1,$2,'Actual independently reviewed duplicate evidence',$3)",[id(11),id(12),id(key)]));
await test('identity proposals require governance evidence and preserve source rows',async()=>{await as(1,()=>assert.rejects(()=>q("select x1_propose($1,$2,'Unauthorized merge attempt',$3)",[id(11),id(12),id(50)])));candidate=await propose();assert.equal(await propose(),candidate);assert.equal((await as(5,()=>scalar('select x1_candidates()'))).length,0);assert.equal(await scalar('select count(*)::int from patient_profiles'),2)});
await test('both source owners must confirm; governance cannot impersonate consent',async()=>{await as(4,()=>assert.rejects(()=>q('select x1_decide($1,true)',[candidate])));await as(1,()=>q('select x1_decide($1,true)',[candidate]));await as(4,()=>assert.rejects(()=>q("select x1_link($1,'Clinician and identity evidence reviewed')",[candidate]),/Both/));await as(2,()=>q('select x1_decide($1,true)',[candidate]))});
await test('link is idempotent and never grants access to canonical clinical records',async()=>{const link=()=>as(4,()=>scalar("select x1_link($1,'Clinician and identity evidence reviewed')",[candidate]));assert.equal(await link(),await link());const r=await as(1,()=>scalar('select x1_identity($1)',[id(11)]));assert.equal(r.canonical_reference,id(12));assert.equal(r.authorization_patient_id,id(11));await as(1,()=>assert.rejects(()=>q('select s1_snapshot_context($1)',[id(12)])));assert.equal(await scalar('select patient_id from encounters where id=$1',[id(21)]),id(11))});
await test('inverse or chained identity links cannot create cycles',async()=>{const c=await as(4,()=>scalar("select x1_propose($1,$2,'Actual inverse review request',$3)",[id(12),id(11),id(51)]));await as(1,()=>q('select x1_decide($1,true)',[c]));await as(2,()=>q('select x1_decide($1,true)',[c]));await as(4,()=>assert.rejects(()=>q("select x1_link($1,'Inverse topology review attempt')",[c]),/topology/))});
await test('owner withdrawal reverses link and keeps immutable historical source evidence',async()=>{await as(1,()=>q('select x1_decide($1,false)',[candidate]));assert.equal((await as(1,()=>scalar('select x1_identity($1)',[id(11)]))).canonical_reference,id(11));assert.equal(await scalar('select count(*)::int from patient_identity_links'),1);assert.equal(await scalar('select count(*)::int from patient_identity_links where active'),0);assert.equal(await scalar('select count(*)::int from encounters'),1)});
await test('changed demographics invalidate stale merge consent and admin unmerge retains history',async()=>{const c=await propose(52);await as(1,()=>q('select x1_decide($1,true)',[c]));await as(2,()=>q('select x1_decide($1,true)',[c]));await q("update patient_profiles set full_name='Changed source identity' where id=$1",[id(11)]);await as(4,()=>assert.rejects(()=>q("select x1_link($1,'Review based on old demographics')",[c]),/changed/));const fresh=await propose(53);await as(1,()=>q('select x1_decide($1,true)',[fresh]));await as(2,()=>q('select x1_decide($1,true)',[fresh]));await as(4,()=>q("select x1_link($1,'Reviewed updated identities')",[fresh]));await as(4,()=>q("select x1_unlink($1,'Operator reversed confirmed alias')",[fresh]));assert.equal(await scalar('select count(*)::int from patient_identity_links where active'),0);assert.ok(await scalar("select count(*)::int from patient_identity_events where action='UNLINKED'"))});
console.log(passed+' identity alias tests passed');await db.close();
