import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);

await q('insert into auth.users(id) values($1)',[id(90)]);await q("update profiles set role='ADMIN' where id=$1",[id(90)]);
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}

let integration=await as(90,()=>scalar("select x2_register('HIS_HMIS','Actual adapter','SANDBOX','https://fixture.invalid','SERVER_ONLY_REF',$1,$2)",[id(40),id(70)]));await as(90,()=>q("select x2_enable($1,true,1,'Reviewed server configuration')",[integration]));let run=await as(8,()=>scalar('select x2_sync($1,$2)',[integration,id(71)]));
const event=(r,state,key,error=null)=>service(()=>q('select x2_sync_event($1,$2,$3,$4,$5,$6)',[r,state,'fixture-source',key,state==='SUCCEEDED'?0:null,error]));
await test('transient failures record backoff and cannot retry early or bypass via initial sync',async()=>{await event(run,'RUNNING','start-a');await event(run,'FAILED','fail-a','TIMEOUT');const r=(await q('select failure_class,next_retry_at,retry_count from integration_sync_runs where id=$1',[run])).rows[0];assert.equal(r.failure_class,'TRANSIENT');assert.ok(r.next_retry_at);await as(8,()=>assert.rejects(()=>q('select x2_retry($1,$2)',[run,id(72)]),/eligible/));await as(8,()=>assert.rejects(()=>q('select x2_sync($1,$2)',[integration,id(72)]),/bounded/))});
await test('eligible retry is idempotent and real success clears active pending work',async()=>{await q("update integration_sync_runs set next_retry_at=now()-interval '1 second' where id=$1",[run]);const retry=()=>as(8,()=>scalar('select x2_retry($1,$2)',[run,id(72)]));const r=await retry();assert.equal(await retry(),r);assert.equal(await scalar('select retry_count from integration_sync_runs where id=$1',[r]),1);await event(r,'RUNNING','start-b');await event(r,'SUCCEEDED','done-b');assert.ok((await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0].last_successful_sync)});
await test('terminal failure has no retry eligibility',async()=>{run=await as(8,()=>scalar('select x2_sync($1,$2)',[integration,id(73)]));await event(run,'RUNNING','start-c');await event(run,'FAILED','fail-c','AUTHENTICATION_REJECTED');assert.equal(await scalar('select failure_class from integration_sync_runs where id=$1',[run]),'TERMINAL');await as(8,()=>assert.rejects(()=>q('select x2_retry($1,$2)',[run,id(74)]),/terminal/))});
await test('retry budget is bounded to three and does not spin indefinitely',async()=>{await as(90,()=>q("select x2_enable($1,true,2,'New reviewed adapter configuration')",[integration]));run=await as(8,()=>scalar('select x2_sync($1,$2)',[integration,id(75)]));for(let i=0;i<4;i++){await event(run,'RUNNING','budget-start-'+i);await event(run,'FAILED','budget-fail-'+i,'RATE_LIMIT');if(i<3){await q("update integration_sync_runs set next_retry_at=now()-interval '1 second' where id=$1",[run]);run=await as(8,()=>scalar('select x2_retry($1,$2)',[run,id(76+i)]));}}await as(8,()=>assert.rejects(()=>q('select x2_retry($1,$2)',[run,id(79)]),/exhausted/));assert.equal(await scalar('select retry_count from integration_sync_runs where id=$1',[run]),3)});
await test('stale and disabled health are distinct, no endpoint secret configuration leaks',async()=>{await service(()=>q("select x2_observe($1,3,'CONFIGURED','OK',null,now()-interval '2 hours',now()-interval '1 hour','fixture-source','old-observation')",[integration]));let h=(await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0];assert.equal(h.truth_state,'STALE');assert.doesNotMatch(JSON.stringify(h),/SERVER_ONLY_REF|endpoint_origin|config_ref/);await as(9,()=>assert.rejects(()=>q('select x2_health($1)',[id(40)])));await as(90,()=>q("select x2_enable($1,false,3,'Disable exhausted integration for review')",[integration]));h=(await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0];assert.equal(h.truth_state,'DISABLED');await as(8,()=>assert.rejects(()=>q('select x2_retry($1,$2)',[run,id(79)]),/current/))});
console.log(passed+' integration retry tests passed');await db.close();
