import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);

await q('insert into auth.users(id) values($1)',[id(90)]);await q("update profiles set role='ADMIN' where id=$1",[id(90)]);
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
let integration,run;
await test('integration metadata is governance-only secret-free and disabled by default',async()=>{await as(8,()=>assert.rejects(()=>q("select x2_register('LIS_RIS_PACS','Actual provider','SANDBOX','https://fixture.invalid','FIXTURE_LIS',$1,$2)",[id(40),id(50)])));await as(90,()=>assert.rejects(()=>q("select x2_register('LIS_RIS_PACS','Actual provider','SANDBOX','https://fixture.invalid?key=secret','FIXTURE_LIS',$1,$2)",[id(40),id(50)]),/origin/));integration=await as(90,()=>scalar("select x2_register('LIS_RIS_PACS','Actual provider','SANDBOX','https://fixture.invalid','FIXTURE_LIS',$1,$2)",[id(40),id(50)]));assert.equal((await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0].health,'DISABLED');await as(9,()=>assert.rejects(()=>q('select x2_health($1)',[id(40)])))});
await test('enabling is not evidence of configured authentication or connectivity',async()=>{await as(90,()=>q("select x2_enable($1,true,1,'Operator enabled actual adapter configuration')",[integration]));const h=(await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0];assert.match(h.health,/UNKNOWN/);assert.match(h.auth_state,/REQUIRED/);await as(90,()=>assert.rejects(()=>q("select x2_observe($1,2,'CONFIGURED','OK',null,now(),now()+interval '1 hour','fixture-source','fixture-event')",[integration])))});
await test('trusted evidence has bounded freshness and stale state remains unknown',async()=>{await service(()=>q("select x2_observe($1,2,'CONFIGURED','OK',null,now()-interval '2 hours',now()-interval '1 hour','fixture-source','fixture-stale')",[integration]));assert.match((await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0].health,/UNKNOWN/);await service(()=>q("select x2_observe($1,2,'CONFIGURED','OK',null,now(),now()+interval '1 hour','fixture-source','fixture-fresh')",[integration]));assert.equal((await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0].health,'OK')});
await test('queued sync is not success and adapter transitions require actual receipt',async()=>{const request=()=>as(8,()=>scalar('select x2_sync($1,$2)',[integration,id(51)]));run=await request();assert.equal(await request(),run);assert.equal(await scalar('select state from integration_sync_runs where id=$1',[run]),'QUEUED');await service(()=>assert.rejects(()=>q("select x2_sync_event($1,'SUCCEEDED','fixture-source','fixture-done',0)",[run]),/transition/));await service(()=>q("select x2_sync_event($1,'RUNNING','fixture-source','fixture-start')",[run]));await service(()=>q("select x2_sync_event($1,'SUCCEEDED','fixture-source','fixture-done',0)",[run]));assert.ok((await as(8,()=>scalar('select x2_health($1)',[id(40)])))[0].last_successful_sync)});
await test('configuration revision invalidates stale callbacks and pending retries',async()=>{const pending=await as(8,()=>scalar('select x2_sync($1,$2)',[integration,id(52)]));await as(90,()=>q("select x2_enable($1,false,2,'Disable pending source integration')",[integration]));assert.equal(await scalar('select state from integration_sync_runs where id=$1',[pending]),'CANCELLED');await service(()=>assert.rejects(()=>q("select x2_sync_event($1,'RUNNING','fixture-source','stale-event')",[pending]),/current/));await service(()=>assert.rejects(()=>q("select x2_observe($1,2,'CONFIGURED','OK',null,now(),now()+interval '1 hour','fixture-source','stale-health')",[integration]),/revision/));assert.equal(await scalar('select count(*)::int from integration_sync_events'),2)});
console.log(passed+' integration registry tests passed');await db.close();
