import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}');update profiles set role='ADMIN' where id='${id(9)}';insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','LAB','Imaging fixture','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Imaging site','DIAGNOSTIC_LAB');insert into lab_test_capabilities(lab_provider_id,diagnostic_test_id) values('${id(18)}','${id(22)}');`);
await as(8,()=>q("select h1_set_member($1,$2,'CLINICIAN',true)",[id(40),id(6)]));

async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
let machine,order,replacement;const observed=new Date().toISOString();
await test('machine registration is assigned-lab scoped and idempotent without fake connectivity',async()=>{const reg=()=>as(8,()=>scalar("select r3_machine('Actual analyzer','Actual manufacturer','Actual model','ASTM',$1)",[id(50)]));machine=await reg();assert.equal(await reg(),machine);await as(4,()=>assert.rejects(()=>q("select r3_machine('Unauthorized','Maker','Model','JSON',$1)",[id(51)])));const w=await as(8,()=>scalar('select r3_quality_worklist()'));assert.match(w.machines[0].integration_state,/UNKNOWN/);assert.match(w.machines[0].quality_state,/UNKNOWN/)});
await test('machine health needs trusted source evidence and stale health is unknown',async()=>{await as(8,()=>assert.rejects(()=>q("select r3_health($1,'CONNECTED',now(),now()+interval '1 hour','fixture-source','fixture-health')",[machine])));await service(()=>q("select r3_health($1,'CONNECTED',now()-interval '2 hours',now()-interval '1 hour','fixture-source','fixture-health')",[machine]));assert.match((await as(8,()=>scalar('select r3_quality_worklist()'))).machines[0].integration_state,/UNKNOWN/)});
await test('QC assessments preserve actual observations and do not verify patient results',async()=>{const quality=()=>as(8,()=>scalar("select r3_quality($1,'fixture-control','FAIL',$2::jsonb,'Control outside operator-validated limits',$3,$4)",[machine,JSON.stringify({control_value:12,expected_min:1,expected_max:2}),observed,id(52)]));assert.equal(await quality(),await quality());assert.equal((await as(8,()=>scalar('select r3_quality_worklist()'))).machines[0].quality_state,'FAIL');assert.equal(await scalar('select count(*)::int from lab_results'),0);await as(4,()=>assert.rejects(()=>q("select r3_quality($1,'fixture-control','PASS','{}','Unauthorized QC entry',now(),$2)",[machine,id(53)])))});
await test('capability updates reuse actual catalog and reject unauthorized roles',async()=>{await as(8,()=>q('select r3_capability($1,true)',[id(22)]));await as(4,()=>assert.rejects(()=>q('select r3_capability($1,false)',[id(22)])));await as(3,()=>q('select p0_create_orders($1,$2::uuid[])',[id(21),[id(22)]]));order=await scalar('select id from lab_orders');await as(1,()=>q("select p0_select_destination($1,'LAB',$2)",[order,id(40)]));await as(8,()=>q("select p0_specimen_step($1,'COLLECT','QC-SAMPLE')",[order]));const sample=await scalar('select sample_code from lab_specimens where lab_order_id=$1',[order]);await as(8,()=>q("select p0_specimen_step($1,'RECEIVE',$2)",[order,sample]));await as(8,()=>q("select p0_specimen_step($1,'REJECT',$2,null,'Actual inadequate sample')",[order,sample]))});
await test('recollection preserves rejected sample and creates fresh unassigned doctor order',async()=>{await as(8,()=>assert.rejects(()=>q("select r3_recollect($1,'Actual clinician reassessment',$2)",[order,id(54)])));const recollect=()=>as(3,()=>scalar("select r3_recollect($1,'Actual clinician reassessment',$2)",[order,id(54)]));replacement=await recollect();assert.equal(await recollect(),replacement);assert.notEqual(replacement,order);const r=(await q('select status,lab_provider_id,collection_centre_id from lab_orders where id=$1',[replacement])).rows[0];assert.equal(r.status,'ORDERED');assert.equal(r.lab_provider_id,null);assert.equal(r.collection_centre_id,null);assert.equal(await scalar('select status from lab_specimens where lab_order_id=$1',[order]),'REJECTED');assert.equal((await as(8,()=>scalar('select r3_quality_worklist()'))).rejected[0].replacement_order_id,replacement);assert.equal(await scalar('select count(*)::int from lab_specimens'),1)});
console.log(passed+' lab quality and recollection tests passed');await db.close();
