import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`b0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){await f();passed++;console.log('PASS '+name)}
await q('insert into auth.users(id) values($1),($2)',[id(1),id(2)]);await q("update profiles set role='ADMIN' where id=$1",[id(1)]);

let feedback,candidate,example,dataset,run,model;
await test('untrusted corrections do not become training examples automatically',async()=>{await as(2,()=>q("select m2_feedback($1,'Untrusted correction without consent',false,$2)",[id(10),id(11)]));assert.equal(await scalar('select count(*)::int from ai_learning_candidates'),0);feedback=await as(2,()=>scalar("select m2_feedback($1,'Opt-in correction for independent review',true,$2)",[id(10),id(12)]));candidate=(await as(1,()=>scalar('select m2_candidates()')))[0].id;assert.equal(await scalar('select count(*)::int from ai_training_examples'),0)});
const content={input:'Deidentified operational example',expected_output:'No supporting record available',task:'SOURCE_SELECTION',language:'English'};
await test('approval requires independent explicit de-identification review',async()=>{await as(2,()=>assert.rejects(()=>q('select m2_review($1,$2::jsonb,$3,true)',[candidate,JSON.stringify(content),'Self approval is forbidden'])));await as(1,()=>assert.rejects(()=>q('select m2_review($1,$2::jsonb,$3,false)',[candidate,JSON.stringify(content),'Reviewed source content'])));example=await as(1,()=>scalar('select m2_review($1,$2::jsonb,$3,true)',[candidate,JSON.stringify(content),'Identifiers removed and expected output reviewed']));await as(1,()=>assert.rejects(()=>q('select m2_review($1,$2::jsonb,$3,true)',[candidate,JSON.stringify(content),'Cannot overwrite approved example'])))});
await test('immutable dataset exports only reviewed content without raw feedback or identity',async()=>{dataset=await as(1,()=>scalar("select m2_dataset('Fixture dataset','v1',$1)",[[example]]));assert.equal(dataset,await as(1,()=>scalar("select m2_dataset('Fixture dataset','v1',$1)",[[example]])));await as(1,()=>assert.rejects(()=>q('select m2_export($1)',[dataset])));const x=await service(()=>scalar('select m2_export($1)',[dataset]));assert.deepEqual(x.examples,[content]);assert.doesNotMatch(JSON.stringify(x),/Opt-in correction|actor_user_id|interaction_ref/)});
await test('training requests do not claim training completion and require real adapter sequence',async()=>{run=await as(1,()=>scalar("select m2_training($1,'fixture-recipe-v1')",[dataset]));assert.equal(await scalar('select state from ai_training_runs where id=$1',[run]),'REQUESTED');await service(()=>assert.rejects(()=>q("select m2_training_result($1,'fixture-offline-run','COMPLETED',$2)",[run,'a'.repeat(64)]),/transition/));await service(()=>q("select m2_training_result($1,'fixture-offline-run','RUNNING')",[run]));await service(()=>q("select m2_training_result($1,'fixture-offline-run','COMPLETED',$2)",[run,'a'.repeat(64)]));model=await as(1,()=>scalar("select m1_register('Fixture owned model','v1','OWN_MODEL','FIXTURE_OWN',array['SOURCE_SELECTION'],array['English'],$1)",['a'.repeat(64)]));await as(1,()=>q('select m2_checkpoint($1,$2)',[model,run]))});
await test('checkpoint still requires evaluation approval before serving',async()=>{await as(1,()=>assert.rejects(()=>q("select m1_deploy('SOURCE_SELECTION','English',$1,0,'Attempt before evaluation')",[model])));const scores={English:{cases:20,unsupported_claims:0,unsafe_actions:0,isolation_failures:0,citation_accuracy:1}};const e=await service(()=>scalar('select m1_evaluate($1,$2,$3::jsonb,$4)',[model,'fixture-suite',JSON.stringify(scores),'fixture-eval']));await as(1,()=>q("select m1_approve($1,'Independent test report reviewed')",[e]));await as(1,()=>q("select m1_deploy('SOURCE_SELECTION','English',$1,0,'Approved isolated checkpoint')",[model]));assert.equal((await service(()=>scalar("select m1_route('SOURCE_SELECTION','English')"))).primary.id,model)});
await test('withdrawal blocks future export training and linked serving without deleting provenance',async()=>{await as(1,()=>assert.rejects(()=>q('select m2_withdraw($1)',[feedback])));await as(2,()=>q('select m2_withdraw($1)',[feedback]));await service(()=>assert.rejects(()=>q('select m2_export($1)',[dataset]),/withdrawn/));await as(1,()=>assert.rejects(()=>q("select m2_training($1,'fixture-recipe-v1')",[dataset])));await service(()=>assert.rejects(()=>q("select m1_route('SOURCE_SELECTION','English')"),/CONFIGURATION/));assert.equal(await scalar('select count(*)::int from ai_training_examples'),1);assert.equal(await scalar('select count(*)::int from ai_training_checkpoints'),1)});
console.log(passed+' owned-model learning tests passed');await db.close();
