import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`b0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){await f();passed++;console.log('PASS '+name)}
await q('insert into auth.users(id) values($1),($2)',[id(1),id(2)]);await q("update profiles set role='ADMIN' where id=$1",[id(1)]);

const rows=[{source_code:'fixture-a',generic_name:'Synthetic catalog fixture',strength:'fixture strength',dosage_form:'fixture form',aliases:['fixture alias']},{source_code:'fixture-b',generic_name:'Second fixture',active:false}];
const imp=(v='v1',r=rows,dry=false,assurance='DEMO',key=50)=>as(1,()=>scalar('select k1_import($1,$2,$3,$4,current_date,$5,$6,$7)',['Fixture source',v,'Fixture evidence only',assurance,JSON.stringify(r),id(key),dry]));
let batch;
await test('dry-run validates without persistence and wrong role cannot import',async()=>{assert.equal((await imp('v1',rows,true)).valid,true);assert.equal(await scalar('select count(*)::int from master_import_batches'),0);await as(2,()=>assert.rejects(()=>q("select k1_import('Fixture','v1','Evidence','DEMO',current_date,'[]',$1)",[id(50)])));const invalid=await imp('bad',[{...rows[0],stock:99}],true);assert.equal(invalid.valid,false);assert.equal((await imp('bad',[{...rows[0],nlem:true}],true)).valid,false)});
await test('source-version deduplicates and conflicting import is rejected',async()=>{batch=(await imp()).batch_id;assert.equal((await imp()).batch_id,batch);await assert.rejects(()=>imp('v1',[{...rows[0],generic_name:'Changed'}]),/conflict/);assert.equal((await imp('dup',[rows[0],rows[0]],true)).valid,false)});
await test('demo is explicit and does not imply inventory or official verification',async()=>{assert.equal((await as(2,()=>scalar('select k1_medicines()'))).items.length,0);const r=await as(2,()=>scalar("select k1_medicines(p_query=>'fixture alias',p_include_demo=>true)"));assert.equal(r.items.length,1);assert.equal(r.items[0].assurance,'DEMO');assert.equal(r.items[0].nlem,null);assert.equal(r.items[0].stock,undefined);assert.equal(await scalar('select count(*)::int from pharmacy_inventory'),0)});
await test('active filtering, exact lookup and stable pagination use stored rows',async()=>{const r=await as(2,()=>scalar('select k1_medicines(p_include_demo=>true,p_active=>null,p_limit=>1)'));assert.equal(r.items.length,1);const next=await as(2,()=>scalar('select k1_medicines(p_include_demo=>true,p_active=>null,p_after=>$1)',[r.next_after]));assert.equal(next.items.length,1);assert.notEqual(next.items[0].id,r.items[0].id);assert.equal((await as(2,()=>scalar('select k1_medicines(p_include_demo=>true,p_active=>false)'))).items.length,1);assert.equal((await as(2,()=>scalar('select k1_medicines(p_include_demo=>true,p_id=>$1,p_active=>null)',[r.items[0].id]))).items.length,1)});
await test('new version supersedes without deletion and disabling restores prior version',async()=>{const newer=await imp('v2',[{...rows[0],active:false}],false,'SOURCE_RECORDED',51);assert.equal((await as(2,()=>scalar('select k1_medicines(p_include_demo=>true)'))).items.length,0);await as(2,()=>assert.rejects(()=>q("select k1_disable_batch($1,'Not authorized')",[newer.batch_id])));await as(1,()=>q("select k1_disable_batch($1,'Withdraw erroneous source version')",[newer.batch_id]));assert.equal((await as(2,()=>scalar('select k1_medicines(p_include_demo=>true)'))).items.length,1);assert.equal(await scalar('select count(*)::int from medicine_master'),3);await as(2,()=>assert.rejects(()=>q('delete from medicine_master')))});
console.log(passed+' medicine master tests passed');await db.close();
