import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);
await q("insert into insurance_policies(id,patient_id,insurer_name,policy_number) values($1,$2,'Recorded payer','POLICY-A'),($3,$4,'Recorded payer','POLICY-B')",[id(60),id(11),id(61),id(12)]);
const invoice=await as(8,()=>scalar("select h3_issue($1,'APPOINTMENT',$2,$3::jsonb,$4)",[id(40),id(43),JSON.stringify([{description:'Recorded service',quantity:1,unit_price:1000}]),id(62)]));
let c;
async function callback(event,payload={},key=event,version=1){await db.exec('set role service_role');try{return await scalar('select i1_external_event($1,$2,$3,$4,$5::jsonb,$6)',[c,version,event,'fixture-adapter-reference',JSON.stringify(payload),'fixture-'+key])}finally{await db.exec('reset role')}}
await test('payer case must match actual invoice patient and facility',async()=>{await as(8,()=>assert.rejects(()=>q("select i1_case($1,$2,'CLAIM',500,$3)",[invoice,id(61),id(63)]),/Matching/));await as(9,()=>assert.rejects(()=>q("select i1_case($1,$2,'CLAIM',500,$3)",[invoice,id(60),id(63)])));c=await as(8,()=>scalar("select i1_case($1,$2,'CLAIM',500,$3)",[invoice,id(60),id(63)]))});
await test('preparation requires patient consent and never fabricates eligibility or submission',async()=>{await as(8,()=>assert.rejects(()=>q('select i1_prepare($1)',[c]),/authorization/));await as(2,()=>assert.rejects(()=>q("select i1_consent($1,'GRANTED',now()+interval '30 days')",[c])));await as(1,()=>q("select i1_consent($1,'GRANTED',now()+interval '30 days')",[c]));assert.equal(await as(8,()=>scalar('select i1_prepare($1)',[c])),1);assert.equal(await as(8,()=>scalar('select i1_prepare($1)',[c])),1);const r=await as(1,()=>scalar('select i1_read($1)',[c]));assert.equal(r.case.state,'READY_FOR_EXTERNAL_SUBMISSION');assert.equal(r.eligibility_state,'UNKNOWN_EXTERNAL_CHECK_REQUIRED')});
await test('ordinary users and administrators cannot forge payer decisions',async()=>{await as(8,()=>assert.rejects(()=>q("select i1_external_event($1,1,'APPROVED','fake-ref','{}','fake-event')",[c]),/permission/));assert.equal(await scalar('select state from payer_cases'),'READY_FOR_EXTERNAL_SUBMISSION')});
await test('trusted adapter contract preserves denial source and supports new submission version',async()=>{await callback('SUBMITTED');await callback('DENIED',{reason:'Source decision requests revised documentation'});assert.equal(await scalar('select state from payer_cases'),'DENIED');assert.equal(await as(8,()=>scalar('select i1_prepare($1)',[c])),2);await assert.rejects(()=>callback('APPROVED',{amount:500},'stale-approval',1),/source event/);await callback('SUBMITTED',{},'submitted-v2',2)});
await test('approval and settlement amounts cannot exceed documented request; retries preserve one event',async()=>{await assert.rejects(()=>callback('APPROVED',{amount:501},'approval-v2',2),/amount/);const r=await callback('APPROVED',{amount:450},'approval-v2',2);assert.equal(await callback('APPROVED',{amount:450},'approval-v2',2),r);await assert.rejects(()=>callback('SETTLED',{amount:451},'settlement',2),/amount/);await callback('SETTLED',{amount:450},'settlement',2);assert.equal(await scalar('select state from payer_cases'),'SETTLED');assert.equal(await scalar('select status from facility_invoices'),'ISSUED')});
await test('revocation blocks new staff disclosure and callbacks without erasing payer source history',async()=>{await as(1,()=>q("select i1_consent($1,'REVOKED')",[c]));await as(8,()=>assert.rejects(()=>q('select i1_read($1)',[c])));await assert.rejects(()=>callback('SETTLED',{amount:450},'settlement',2),/expired/);assert.ok(Number(await scalar('select count(*) from payer_case_events'))>0);assert.equal((await as(1,()=>scalar('select i1_read($1)',[c]))).case.state,'SETTLED')});
console.log(`${passed} payer case tests passed`);await db.close();
