import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);

await q('insert into auth.users(id) values($1)',[id(90)]);await q("update profiles set role='ADMIN' where id=$1",[id(90)]);await q("update provider_practices set state='Actual state',district='Actual district' where id=$1",[id(42)]);
const month=await scalar("select (date_trunc('month',now() at time zone 'Asia/Kolkata')-interval '1 month')::date");const time=await scalar("select (($1::date+interval '10 days') at time zone 'Asia/Kolkata')",[month]);
for(let i=0;i<30;i++){const n=1000+i*10;await q('insert into auth.users(id) values($1)',[id(n)]);await q("insert into patient_profiles(id,user_id,patient_code,full_name) values($1,$2,$3,'Secret patient name')",[id(n+1),id(n),'PULSE-'+i]);await q("insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values($1,$2,$3,$4,$5,'PHYSICAL','CONFIRMED')",[id(n+2),id(n+1),id(13),id(42),new Date(new Date(time).getTime()+i*3600000).toISOString()]);await q('insert into encounters(id,appointment_id,patient_id,doctor_provider_id,started_at) values($1,$2,$3,$4,$5)',[id(n+3),id(n+2),id(n+1),id(13),time]);const node=await scalar("select n.id from care_nodes n join care_episodes e on e.id=n.episode_id where e.encounter_id=$1 and n.kind='CONSULTATION'",[id(n+3)]);if(i<15)await q("insert into care_gaps(patient_id,gap_type,created_at,graph_node_id) values($1,'ACTUAL_SOURCE_GAP',$2,$3)",[id(n+1),time,node]);}
const pulse=(user=90,district='Actual district',facility=null)=>as(user,()=>scalar('select t3_pulse($1,$2,$3,$4)',['Actual state',district,month,facility]));
await test('fixed cohort aggregate is correct with minimum numerator and complement cells',async()=>{const r=await pulse();const m=r.metrics.find(x=>x.metric==='OPEN_CAREGAPS');assert.equal(m.numerator,15);assert.equal(m.denominator,30);assert.equal(m.suppression_state,'RELEASED');assert.equal(r.minimum_cell_size,10)});
await test('empty and tiny metric cells suppress counts instead of returning exact zeros',async()=>{const r=await pulse();const m=r.metrics.find(x=>x.metric==='MEDICINES_DISPENSED');assert.equal(m.numerator,null);assert.equal(m.denominator,null);assert.match(m.suppression_state,/SUPPRESSED/);const empty=await pulse(90,'Unmapped district');assert.ok(empty.metrics.every(x=>x.numerator===null&&x.denominator===null))});
await test('output contains no individual identifiers or clinical narrative',async()=>{const r=await pulse();assert.doesNotMatch(JSON.stringify(r),/patient_id|patient_name|Secret patient|abha|phone|address|10000000-0000-4000-8000-000000001/);assert.ok(r.last_refreshed);assert.match(r.data_freshness,/CURRENT_RECORDED/)});
await test('facility managers are limited to own sourced geography and patients cannot query',async()=>{await assert.rejects(()=>pulse(1));await assert.rejects(()=>pulse(8));await assert.rejects(()=>pulse(9,'Actual district',id(40)));const r=await pulse(8,'Actual district',id(40));assert.equal(r.metrics.find(x=>x.metric==='OPEN_CAREGAPS').numerator,15);const empty=await pulse(9,'Actual district',id(41));assert.ok(empty.metrics.every(x=>x.denominator===null))});
await test('arbitrary tiny date windows and current incomplete month are denied',async()=>{await as(90,()=>assert.rejects(()=>q("select t3_pulse('Actual state','Actual district',$1::date+1)",[month]),/calendar/));await as(90,()=>assert.rejects(()=>q("select t3_pulse('Actual state','Actual district',date_trunc('month',now())::date)"),/calendar/))});

await test('current stock and capability aggregates use explicit geography and complementary suppression',async()=>{
 for(let i=0;i<30;i++){const n=3000+i*10;await q('insert into auth.users(id) values($1)',[id(n)]);await q("insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values($1,$2,'PHARMACY','Synthetic operator','APPROVED')",[id(n+1),id(n)]);await q("insert into facilities(id,owner_user_id,name,facility_type,state,district,verification_status) values($1,$2,'Synthetic site','PHARMACY','Actual state','Stock district','APPROVED')",[id(n+2),id(n)]);if(i<15){await q("insert into pharmacy_inventory(pharmacy_provider_id,medicine_name,quantity,expiry_date) values($1,'Synthetic stock',1,current_date+1)",[id(n+1)]);await q("insert into facility_capability_updates(facility_id,capability_code,available,observed_at,valid_until,recorded_by) values($1,'FIXTURE',false,now(),now()+interval '1 hour',$2)",[id(n+2),id(n)])}}
 const r=(await pulse(90,'Stock district')).current_operations;assert.equal(r.time_basis,'CURRENT_RECORDED_STATE_NOT_MONTH_COHORT');assert.ok(r.metrics.every(m=>m.numerator===15&&m.denominator===30));assert.doesNotMatch(JSON.stringify(r),/Synthetic|patient_id|provider_id|3000/);
 const own=(await pulse(3000,'Stock district',id(3002))).current_operations;assert.ok(own.metrics.every(m=>m.numerator===null&&m.denominator===null));
});
await test('ambiguous multi-site stock is excluded and expired capability remains stale',async()=>{await q("insert into facilities(id,owner_user_id,name,facility_type,state,district,verification_status) values($1,$2,'Second synthetic site','PHARMACY','Actual state','Stock district','APPROVED')",[id(3900),id(3000)]);await q("update facility_capability_updates set observed_at=now()-interval '2 hours',valid_until=now()-interval '1 hour' where facility_id=$1",[id(3012)]);const r=(await pulse(90,'Stock district')).current_operations;const stock=r.metrics.find(m=>m.metric.includes('STOCK'));assert.equal(stock.numerator,14);assert.equal(stock.denominator,29);const cap=r.metrics.find(m=>m.metric.includes('CAPABILITY'));assert.equal(cap.numerator,14);assert.equal(cap.denominator,31)});
console.log(passed+' district pulse tests passed');await db.close();
