import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);
let dep,entry;
const check=(a=43,key=50,d=dep)=>as(10,()=>scalar('select h1_check_in($1,$2,$3,$4)',[id(40),id(a),d,id(key)]));
await test('facility owner manages memberships; unrelated owner and self-grant fail',async()=>{await as(9,()=>assert.rejects(()=>q("select h1_set_member($1,$2,'RECEPTION',true)",[id(40),id(10)])));await as(10,()=>assert.rejects(()=>q("select h1_set_member($1,$2,'MANAGER',true)",[id(40),id(10)])));await as(8,()=>q("select h1_set_member($1,$2,'RECEPTION',true)",[id(40),id(10)]));await as(8,()=>q("select h1_set_member($1,$2,'CLINICIAN',true)",[id(40),id(3)]));dep=await as(8,()=>scalar("select h1_department($1,'General medicine')",[id(40)]))});
await test('cross-facility department cannot issue token or consume counter',async()=>{const wrong=await as(9,()=>scalar("select h1_department($1,'Other department')",[id(41)]));await assert.rejects(()=>check(43,50,wrong),/Department/);assert.equal(await scalar('select count(*)::int from facility_token_counters'),0)});
await test('check-in persists stable token and retry never increments counter',async()=>{entry=await check();assert.equal(await check(),entry);assert.equal(await scalar('select last_token from facility_token_counters'),1);assert.equal((await as(1,()=>scalar('select h1_my_token($1)',[id(43)]))).token_number,1);await assert.rejects(()=>check(44,50),/conflict/)});
await test('next actual patient gets next token without leaking to other hospital',async()=>{await check(44,51);assert.equal(await scalar('select last_token from facility_token_counters'),2);const date=await scalar("select (now() at time zone 'Asia/Kolkata')::date");const r=(await as(10,()=>q('select * from h1_queue($1,$2)',[id(40),date]))).rows;assert.equal(r.length,2);assert.deepEqual(r.map(x=>x.token_number),[1,2]);assert.equal(r[0].clinical_notes,undefined);await as(9,()=>assert.rejects(()=>q('select * from h1_queue($1,$2)',[id(40),date])));await as(2,()=>assert.rejects(()=>q('select h1_my_token($1)',[id(43)])))});
await test('reception cannot fake consultation completion or write queue directly',async()=>{await as(10,()=>assert.rejects(()=>q("select h1_queue_transition($1,'COMPLETED')",[entry])));await as(10,()=>assert.rejects(()=>q("update reception_queue set state='COMPLETED'")));await as(10,()=>q("select h1_queue_transition($1,'WAITING')",[entry]));await as(10,()=>q("select h1_queue_transition($1,'CALLED')",[entry]))});
await test('actual encounter transitions drive queue; cannot cancel after start',async()=>{const e=await as(3,()=>scalar('select a2_start_encounter($1)',[id(43)]));assert.equal(await scalar('select state from reception_queue where id=$1',[entry]),'IN_CONSULTATION');await as(10,()=>assert.rejects(()=>q("select h1_queue_transition($1,'CANCELLED')",[entry])));await as(3,()=>q("update encounters set chief_complaint='Concern',clinical_notes='Reviewed patient' where id=$1",[e.id]));await as(3,()=>q("select c1_finish_encounter($1,'[]',array[]::uuid[])",[e.id]));assert.equal(await scalar('select state from reception_queue where id=$1',[entry]),'COMPLETED')});
await test('membership revocation blocks subsequent queue reads',async()=>{await as(8,()=>q("select h1_set_member($1,$2,'RECEPTION',false)",[id(40),id(10)]));await as(10,()=>assert.rejects(()=>q('select * from h1_queue($1,current_date)',[id(40)])))});
console.log(`${passed} facility reception tests passed`);await db.close();

