import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`a0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a),scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,f){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await f()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,f){try{await f();passed++;console.log('PASS '+name)}catch(e){throw Error(name+': '+e.message)}}
await db.exec(`insert into auth.users(id) values('${id(1)}'),('${id(2)}'),('${id(3)}');
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','PROV-A','Fixture A'),('${id(12)}','${id(2)}','PROV-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(13)}','${id(3)}','DOCTOR','Fixture doctor','APPROVED');
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','Source complaint','Original note');`);

await q('insert into auth.users(id) values($1)',[id(4)]);await q("update profiles set role='ADMIN' where id=$1",[id(4)]);const ep=await scalar('select id from care_episodes where encounter_id=$1',[id(21)]);let consent;
await test('replay keys and recorded chronology are deterministic source-linked and noneditable',async()=>{const a=await as(1,()=>scalar('select t1_replay($1)',[id(11)]));const b=await as(1,()=>scalar('select t1_replay($1)',[id(11)]));assert.deepEqual(a.items,b.items);assert.equal(new Set(a.items.map(x=>x.event_key)).size,a.items.length);assert.ok(a.items.some(x=>x.source_entity==='appointments'));assert.ok(a.items.some(x=>x.source_entity==='patient_profiles'));assert.ok(a.items.every(x=>x.source_id&&x.recorded_at&&x.provenance));assert.doesNotMatch(JSON.stringify(a.items),/Original note|Source complaint/);await as(1,()=>assert.rejects(()=>q('select * from care_replay_evidence')))});
await test('cursor pages do not repeat evidence and late evidence keeps occurrence separate',async()=>{await q("insert into clinical_source_versions(patient_id,source_kind,source_id,revision,category,occurred_at,verification_state,original,capture_kind) values($1,'late_external_record',$2,1,'DOCUMENTS','2001-01-01','UNVERIFIED','{}','INSERT')",[id(11),id(60)]);const a=await as(1,()=>scalar("select t1_replay($1,'TREATMENT',null,null,null,2)",[id(11)]));const cursor=a.next_cursor;const b=await as(1,()=>scalar("select t1_replay($1,'TREATMENT',null,$2,$3,2)",[id(11),cursor.recorded_at,cursor.event_key]));assert.ok(!a.items.some(x=>b.items.some(y=>y.event_key===x.event_key)));const late=(await as(1,()=>scalar('select t1_replay($1)',[id(11)]))).items.find(x=>x.source_entity==='late_external_record');assert.match(late.occurred_at,/2001/);assert.ok(late.recorded_at>late.occurred_at)});
await test('patient isolation and admin role do not expand clinical replay access',async()=>{await as(2,()=>assert.rejects(()=>q('select t1_replay($1)',[id(11)])));await as(4,()=>assert.rejects(()=>q('select t1_replay($1)',[id(11)])));await as(1,()=>assert.rejects(()=>q("select t1_replay($1,'TREATMENT',$2)",[id(11),id(999)])))});
await test('authorized clinician receives only permitted categories and original episode',async()=>{consent=await as(3,()=>scalar("select a1_request_consent($1,'TREATMENT',array['ENCOUNTERS'],'Review operational history',now(),now()+interval '1 day')",[id(11)]));await as(1,()=>q("select a1_decide_consent($1,'GRANTED')",[consent]));const r=await as(3,()=>scalar("select t1_replay($1,'TREATMENT',$2)",[id(11),ep]));assert.ok(r.items.length);assert.ok(r.items.every(x=>x.episode_id===ep));assert.ok(!r.items.some(x=>x.source_entity==='late_external_record'))});
await test('revoked consent prevents replay even after previous successful pages',async()=>{await as(1,()=>q("select a1_decide_consent($1,'REVOKED')",[consent]));await as(3,()=>assert.rejects(()=>q('select t1_replay($1)',[id(11)]),/consent/))});
console.log(passed+' care replay tests passed');await db.close();
