import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);

await db.exec(`insert into auth.users(id) values('${id(90)}'),('${id(91)}');update profiles set role='ADMIN' where id='${id(91)}';insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(92)}','${id(90)}','LAB','Fixture lab','APPROVED');`);
const tool=(user,name,scope={})=>as(user,()=>scalar('select a3_tool($1,$2::jsonb)',[name,JSON.stringify(scope)]));
const patientTools=['get_patient_snapshot','get_recent_diagnostics','get_prescriptions','get_medicine_fulfilment','get_appointments','get_open_caregaps','get_nextstep','get_caregraph','get_longitudinal_history','get_diagnostic_trends','get_pending_report_reviews','get_active_medicines','get_followup_state'];
await test('all patient tools enforce identity and return dated source or explicit unknown',async()=>{for(const t of patientTools){const r=await tool(1,t,{patient_id:id(11)});assert.equal(r.actor_role,'PATIENT');assert.equal(r.purpose,'AI_ASSISTANCE');await assert.rejects(()=>tool(2,t,{patient_id:id(11)}));}assert.match(JSON.stringify((await tool(1,'get_active_medicines',{patient_id:id(11)})).data),/UNKNOWN/) });
let consent;
await test('doctor AI tools require AI consent and reject revoked grants',async()=>{await assert.rejects(()=>tool(3,'get_patient_snapshot',{patient_id:id(11)}),/consent/);consent=await as(3,()=>scalar("select a1_request_consent($1,'AI_ASSISTANCE',array['ENCOUNTERS'],'Authorized history review',now(),now()+interval '1 day')",[id(11)]));await as(1,()=>q("select a1_decide_consent($1,'GRANTED')",[consent]));assert.equal((await tool(3,'get_patient_snapshot',{patient_id:id(11)})).actor_role,'DOCTOR');await as(1,()=>q("select a1_decide_consent($1,'REVOKED')",[consent]));await assert.rejects(()=>tool(3,'get_patient_snapshot',{patient_id:id(11)}),/consent/)});
await test('hospital tools are scoped to active membership and omit patient identity',async()=>{await as(8,()=>q("select h1_set_member($1,$2,'RECEPTION',true)",[id(40),id(10)]));await as(8,()=>q("select h1_set_member($1,$2,'CLINICIAN',true)",[id(40),id(3)]));const dep=await as(8,()=>scalar("select h1_department($1,'General')",[id(40)]));await as(10,()=>q('select h1_check_in($1,$2,$3,$4)',[id(40),id(43),dep,id(70)]));for(const t of ['get_hospital_queue','get_admissions','get_beds','get_discharge_pending','get_facility_workload']){const r=await tool(10,t,{facility_id:id(40)});assert.equal(r.actor_role,'FACILITY');assert.doesNotMatch(JSON.stringify(r.data),/patient_name|patient_id|Fixture A/);await assert.rejects(()=>tool(9,t,{facility_id:id(40)}));}await as(8,()=>q("select h1_set_member($1,$2,'RECEPTION',false)",[id(40),id(10)]));await assert.rejects(()=>tool(10,'get_hospital_queue',{facility_id:id(40)}))});
await test('pharmacy tools use only assigned pharmacy source rows',async()=>{await q("insert into pharmacy_inventory(pharmacy_provider_id,medicine_name,quantity,expiry_date) values($1,'Actual fixture medicine',0,current_date+10)",[id(14)]);for(const t of ['get_inventory','get_low_stock','get_expiry','get_pharmacy_fulfilment','get_purchases','get_sales_summary']){assert.equal((await tool(4,t)).actor_role,'PHARMACY');await assert.rejects(()=>tool(1,t));}assert.equal((await tool(7,'get_inventory')).data.length,0);assert.equal((await tool(4,'get_low_stock')).data[0].quantity,0)});
await test('lab tools and doctor critical worklist use role-scoped nonclinical projections',async()=>{for(const t of ['get_pathology_worklist','get_study_worklist','get_critical_worklist']){assert.equal((await tool(90,t)).actor_role,'LAB');await assert.rejects(()=>tool(4,t));}assert.equal((await tool(3,'get_critical_worklist')).actor_role,'DOCTOR')});
await test('worker tools cannot search patients or escape assigned task scope',async()=>{for(const t of ['get_assigned_tasks','get_worker_delegations','get_worker_sync','get_worker_next_action']){assert.equal((await tool(5,t)).actor_role,'WORKER');await assert.rejects(()=>tool(5,t,{patient_id:id(11)}));await assert.rejects(()=>tool(5,t,{task_id:id(999)}));}});
await test('admin tools are governance-only and unsupported tools never execute SQL',async()=>{for(const t of ['get_verification_queue','get_model_governance']){assert.equal((await tool(91,t)).actor_role,'ADMIN');await assert.rejects(()=>tool(1,t));}await assert.rejects(()=>tool(91,'select * from patient_profiles'),/UNAVAILABLE/);await assert.rejects(()=>tool(91,'get_model_governance',{role:'ADMIN'}),/INVALID/);assert.ok(await scalar('select count(*)::int from ai_tool_audit'))});
console.log(passed+' role AI database tests passed');await db.close();
