import assert from 'node:assert/strict';
import fs from 'node:fs';
import {db} from './migrations.mjs';
const id=n=>`53000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);
const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
const preview=fs.readFileSync('scripts/staging-cleanup-preview.sql','utf8');
const destructive=fs.readFileSync('scripts/staging-cleanup.sql','utf8');
await db.exec(`alter table auth.users add column email text;
insert into auth.users(id,email) values('${id(1)}','swasthyasetu.test.cleanup@example.com'),('${id(2)}','test.staging.cleanup@example.com'),('${id(3)}','legitimate.demo@example.com'),('${id(4)}','test.person@example.com');
insert into patient_profiles(id,user_id,patient_code) values('${id(101)}','${id(1)}','CLEANUP-SYNTHETIC'),('${id(103)}','${id(3)}','CLEANUP-PROTECTED');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(102)}','${id(2)}','DOCTOR','Synthetic doctor','APPROVED');
insert into facilities(id,owner_user_id,name,facility_type,verification_status) values('${id(200)}','${id(2)}','TEST DEMO Cleanup','CLINIC','APPROVED');
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(201)}','${id(101)}','${id(102)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes) values('${id(202)}','${id(201)}','${id(101)}','${id(102)}','Cleanup test','Synthetic');
insert into prescriptions(id,patient_id,doctor_provider_id,encounter_id,status) values('${id(203)}','${id(101)}','${id(102)}','${id(202)}','ACTIVE');
insert into prescription_items(prescription_id,medicine_name) values('${id(203)}','Synthetic medicine');`);
const before=await scalar('select count(*)::int from auth.users');
await db.exec(preview);
assert.equal(await scalar('select count(*)::int from auth.users'),before);
assert.equal(await scalar('select count(*)::int from encounters'),1);
console.log('PASS preview executes FK cleanup then rolls back all changes');
await db.exec(destructive);
const report=(await q('select * from cleanup_report')).rows[0];
assert.equal(Number(report.synthetic_auth_users),0);assert.equal(Number(report.synthetic_facilities),0);assert.equal(Number(report.synthetic_operational_rows),0);
for(const t of ['encounters','appointments','prescriptions','prescription_items','care_episodes'])assert.equal(await scalar(`select count(*)::int from ${t}`),0,t);
assert.equal(await scalar('select count(*)::int from clinical_source_versions where patient_id=$1',[id(101)]),0);
assert.ok(await scalar('select count(*)::int from clinical_source_versions where patient_id=$1',[id(103)]));
assert.equal(await scalar('select count(*)::int from auth.users'),2);
assert.equal(await scalar('select count(*)::int from patient_profiles'),1);
console.log('PASS commit removes synthetic profiles/workflows and preserves legitimate example.com accounts');
// A repeated run in a new connection has no temporary state. Drop only this test connection's temp state.
await db.exec('drop table cleanup_rows,cleanup_keys,cleanup_report; drop function pg_temp.cleanup_capture();');
await db.exec(destructive);assert.equal(Number((await q('select * from cleanup_report')).rows[0].selected_rows),0);
console.log('PASS already-clean execution is verified and idempotent');
await db.exec('drop table cleanup_rows,cleanup_keys,cleanup_report; drop function pg_temp.cleanup_capture();');
await db.exec(`insert into auth.users(id,email) values('${id(2)}','test.staging.cleanup@example.com');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(102)}','${id(2)}','DOCTOR','Synthetic doctor','APPROVED');
insert into appointments(patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(103)}','${id(102)}',now(),'PHYSICAL','CONFIRMED');`);
await assert.rejects(()=>db.exec(preview),/protected patient workflow/);await db.exec('rollback');
assert.equal(await scalar('select count(*)::int from appointments'),1);
assert.equal(await scalar('select count(*)::int from auth.users'),3);
console.log('PASS cleanup refuses a synthetic actor linked to legitimate patient workflow');
console.log('4 staging cleanup tests passed');await db.close();
