import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);
await db.exec(`insert into auth.users(id) values('${id(8)}'),('${id(9)}'),('${id(10)}');insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values('${id(18)}','${id(8)}','FACILITY','Hospital A','APPROVED'),('${id(19)}','${id(9)}','FACILITY','Hospital B','APPROVED');insert into facilities(id,owner_user_id,name,facility_type) values('${id(40)}','${id(8)}','Hospital A','HOSPITAL'),('${id(41)}','${id(9)}','Hospital B','HOSPITAL');insert into provider_practices(id,provider_id,facility_id,practice_name) values('${id(42)}','${id(13)}','${id(40)}','Clinic A');insert into appointments(id,patient_id,doctor_provider_id,practice_id,scheduled_at,mode,status) values('${id(43)}','${id(11)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '10 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED'),('${id(44)}','${id(12)}','${id(13)}','${id(42)}',(date_trunc('day',now() at time zone 'Asia/Kolkata')+interval '11 hours') at time zone 'Asia/Kolkata','PHYSICAL','CONFIRMED');`);

await q('insert into auth.users(id) values($1)',[id(90)]);await q("update profiles set role='ADMIN' where id=$1",[id(90)]);
async function service(f){await db.exec('set role service_role');try{return await f()}finally{await db.exec('reset role')}}
await q("insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values($1,$2,$3,now()-interval '1 minute','TELECONSULT','CONFIRMED'),($4,$2,$3,now()-interval '3 hours','TELECONSULT','CONFIRMED')",[id(91),id(11),id(13),id(92)]);
let session,integration,intent,participant;
await test('only actual teleconsult participants can open within expiry',async()=>{for(const n of [2,6,8,90])await as(n,()=>assert.rejects(()=>q('select t4_open($1)',[id(91)]),/participant/));await as(1,()=>assert.rejects(()=>q('select t4_open($1)',[id(20)]),/participant/));await as(1,()=>assert.rejects(()=>q('select t4_open($1)',[id(92)]),/expired/));const r=await as(1,()=>scalar('select t4_open($1)',[id(91)]));session=r.session_id;assert.equal(r.provider_state,'UNCONFIGURED');assert.equal(r.recording_enabled,false);assert.equal((await as(3,()=>scalar('select t4_open($1)',[id(91)]))).session_id,session);assert.equal((await as(1,()=>scalar('select t4_join_intent($1,$2)',[session,id(93)]))).status,'PROVIDER_UNAVAILABLE');await service(()=>assert.rejects(()=>q('select t4_prepare($1)',[session]),/UNAVAILABLE/))});
await test('late provider configuration recovers same room without client secrets',async()=>{integration=await as(90,()=>scalar("select x2_register('VIDEO','Fixture video','SANDBOX','https://fixture.invalid','FIXTURE_VIDEO',null,$1)",[id(94)]));await as(90,()=>q("select x2_enable($1,true,1,'Configured fixture adapter')",[integration]));await as(90,()=>q('select t4_route($1)',[integration]));await as(1,()=>assert.rejects(()=>q('select t4_prepare($1)',[session])));assert.equal((await service(()=>scalar('select t4_prepare($1)',[session]))).config_ref,'FIXTURE_VIDEO');await service(()=>q("select t4_room_ready($1,'room-fixture','room-event')",[session]));await service(()=>q("select t4_room_ready($1,'room-fixture','room-event')",[session]));assert.equal(await scalar("select count(*)::int from teleconsult_events where event_type='ROOM_CREATED'"),1);const r=await as(1,()=>scalar('select t4_open($1)',[id(91)]));assert.equal(r.state,'WAITING');assert.equal(r.config_ref,undefined);assert.equal(r.external_room_reference,undefined)});
await test('join issuance is service-only participant-bound and idempotent',async()=>{await as(2,()=>assert.rejects(()=>q('select t4_join_intent($1,$2)',[session,id(95)])));const r=await as(1,()=>scalar('select t4_join_intent($1,$2)',[session,id(95)]));intent=r.intent_id;assert.equal((await as(1,()=>scalar('select t4_join_intent($1,$2)',[session,id(95)]))).intent_id,intent);await as(3,()=>assert.rejects(()=>q('select t4_join_intent($1,$2)',[session,id(95)]),/conflict/));await as(1,()=>assert.rejects(()=>q('select t4_issue_context($1)',[intent])));const c=await service(()=>scalar('select t4_issue_context($1)',[intent]));participant=c.participant_id;assert.equal(c.role,'PATIENT');assert.equal(c.recording_enabled,false);await service(()=>q("select t4_token_issued($1,'issuance-fixture')",[intent]));await service(()=>q("select t4_token_issued($1,'issuance-fixture')",[intent]));await as(1,()=>assert.rejects(()=>q('select * from teleconsult_sessions')))});
await test('connection receipts permit reconnect but cannot complete consultation',async()=>{await service(()=>q("select t4_connection($1,$2,'JOINED','connection-fixture','join-1')",[session,participant]));await service(()=>q("select t4_connection($1,$2,'LEFT','connection-fixture','leave-1')",[session,participant]));await service(()=>q("select t4_connection($1,$2,'JOINED','connection-fixture','join-2')",[session,participant]));assert.equal(await scalar('select state from teleconsult_participants where id=$1',[participant]),'JOINED');assert.equal(await scalar('select status from appointments where id=$1',[id(91)]),'CONFIRMED')});
await test('disabled integration invalidates both issuance and new connection callbacks',async()=>{await as(90,()=>q("select x2_enable($1,false,2,'Stop fixture adapter')",[integration]));await service(()=>assert.rejects(()=>q('select t4_issue_context($1)',[intent]),/revoked/));await service(()=>assert.rejects(()=>q("select t4_connection($1,$2,'JOINED','connection-fixture','revoked-join')",[session,participant]),/revoked/))});
await test('end request blocks join before provider termination confirmation',async()=>{assert.equal(await as(1,()=>scalar('select t4_request_end($1)',[session])),'ENDING');await as(1,()=>assert.rejects(()=>q('select t4_join_intent($1,$2)',[session,id(96)]),/closed/));assert.equal((await service(()=>scalar('select t4_end_context($1)',[session]))).room_reference,'room-fixture');await as(1,()=>assert.rejects(()=>q('select t4_end_context($1)',[session])));await service(()=>q("select t4_provider_state($1,'ENDED','end-fixture','end-event')",[session]));assert.equal(await as(3,()=>scalar('select t4_request_end($1)',[session])),'ENDED');assert.equal(await scalar('select status from appointments where id=$1',[id(91)]),'CONFIRMED')});
console.log(passed+' teleconsult tests passed');await db.close();
