import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a);const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;throw Error(name+': '+e.message)}};
await db.exec(`insert into auth.users(id) values ${[1,2,3,4,5,6,7].map(n=>`('${id(n)}')`).join(',')};
insert into patient_profiles(id,user_id,patient_code,full_name) values('${id(11)}','${id(1)}','CORE-A','Fixture A'),('${id(12)}','${id(2)}','CORE-B','Fixture B');
insert into provider_profiles(id,user_id,provider_type,full_name,verification_status) values ${[[3,'DOCTOR'],[4,'PHARMACY'],[5,'WORKER'],[6,'DOCTOR'],[7,'PHARMACY']].map(([n,t])=>`('${id(n+10)}','${id(n)}','${t}','Fixture ${t} ${n}','APPROVED')`).join(',')};
insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values('${id(20)}','${id(11)}','${id(13)}',now(),'PHYSICAL','CONFIRMED');
insert into encounters(id,appointment_id,patient_id,doctor_provider_id,chief_complaint,clinical_notes,follow_up_in_days) values('${id(21)}','${id(20)}','${id(11)}','${id(13)}','New complaint','Actual source note',7);
insert into diagnostic_tests(id,test_code,test_name) values('${id(22)}','CORE-TEST','Core test fixture');`);

await as(3,()=>q("select c1_finish_encounter($1,$2::jsonb,array[]::uuid[])",[id(21),JSON.stringify([{medicine_name:'Twin fixture medicine',dose:'1 tablet',frequency:'daily',duration:'3 days',quantity_prescribed:3}])]));const ep=await scalar('select id from care_episodes where encounter_id=$1',[id(21)]);const gap=await scalar("select id from care_gaps where gap_type='FOLLOW_UP_PENDING'");let consent;
await test('Care Twin projects actual source IDs and separates open gaps and closure',async()=>{const r=await as(1,()=>scalar('select t2_twin($1)',[ep]));assert.equal(r.episode.encounter_id,id(21));assert.equal(r.episode.status,'ACTIVE');assert.ok(r.care_gaps.some(x=>x.id===gap&&x.status==='OPEN'));assert.ok(r.nodes.every(x=>x.source_id&&x.id));assert.equal(r.prescriptions.length,1);assert.equal(r.emergencies.length,0);assert.match(r.notice,/not disease simulation/)});
await test('stale operational evidence is explicit and not declared available',async()=>{await q("update care_nodes set updated_at=now()-interval '8 days' where episode_id=$1 and state<>'COMPLETED'",[ep]);const r=await as(1,()=>scalar('select t2_twin($1)',[ep]));assert.ok(r.nodes.some(x=>x.freshness==='STATUS_UNKNOWN_CONFIRMATION_REQUIRED'));assert.equal(r.episode.status,'ACTIVE')});
await test('external uploaded completion claim stays pending and cannot close gap',async()=>{await q("insert into health_records(id,patient_id,record_type,source_type,storage_path,original_filename) values($1,$2,'REPORT','PATIENT_UPLOAD','fixture-external','External source.pdf')",[id(80),id(11)]);const claim=()=>as(1,()=>scalar("select t2_external_completion($1,$2,'Patient reports care completed externally',$3)",[gap,id(80),id(81)]));assert.equal(await claim(),await claim());const r=await as(1,()=>scalar('select t2_twin($1)',[ep]));assert.equal(r.external_claims[0].state,'EXTERNAL_COMPLETION_POSSIBLE_VERIFICATION_PENDING');assert.equal(r.care_gaps.find(x=>x.id===gap).status,'OPEN');assert.equal(await scalar('select verification_status from health_records where id=$1',[id(80)]),'UNVERIFIED')});
await test('wrong patient and unconsented clinician cannot inspect episode',async()=>{await as(2,()=>assert.rejects(()=>q('select t2_twin($1)',[ep])));await as(3,()=>assert.rejects(()=>q('select t2_twin($1)',[ep]),/consent/));consent=await as(3,()=>scalar("select a1_request_consent($1,'TREATMENT',array['ENCOUNTERS'],'Review episode state',now(),now()+interval '1 day')",[id(11)]));await as(1,()=>q("select a1_decide_consent($1,'GRANTED')",[consent]));const r=await as(3,()=>scalar('select t2_twin($1)',[ep]));assert.equal(r.care_gaps.length,0);assert.equal(r.prescriptions.length,0);assert.equal(r.external_claims.length,0)});
await test('revoked treatment consent and separate AI purpose remain enforced',async()=>{await as(3,()=>assert.rejects(()=>q("select t2_twin($1,'AI_ASSISTANCE')",[ep]),/consent/));await as(1,()=>q("select a1_decide_consent($1,'REVOKED')",[consent]));await as(3,()=>assert.rejects(()=>q('select t2_twin($1)',[ep]),/consent/))});
await test('second episode never receives source objects from first episode',async()=>{await q("insert into appointments(id,patient_id,doctor_provider_id,scheduled_at,mode,status) values($1,$2,$3,now(),'PHYSICAL','CONFIRMED')",[id(90),id(11),id(13)]);await q("insert into encounters(id,appointment_id,patient_id,doctor_provider_id) values($1,$2,$3,$4)",[id(91),id(90),id(11),id(13)]);const ep2=await scalar('select id from care_episodes where encounter_id=$1',[id(91)]);const r=await as(1,()=>scalar('select t2_twin($1)',[ep2]));assert.equal(r.external_claims.length,0);assert.equal(r.care_gaps.length,0);assert.equal(r.prescriptions.length,0);assert.equal(r.appointments[0].id,id(90))});
console.log(passed+' care twin tests passed');await db.close();
