import assert from 'node:assert/strict';
import {db} from './migrations.mjs';
const id=n=>`90000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q=(s,a=[])=>db.query(s,a); const scalar=async(s,a=[])=>Object.values((await q(s,a)).rows[0])[0];
async function as(n,fn){await db.exec('set role authenticated');await q("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);try{return await fn()}finally{await db.exec('reset role')}}
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS '+name)}
await db.exec(`insert into auth.users(id) values('${id(1)}'),('${id(2)}'),('${id(3)}');
insert into profiles(id,role,full_name) values('${id(1)}','ADMIN','Admin fixture'),('${id(2)}','LAB','Lab fixture'),('${id(3)}','PATIENT','Other fixture') on conflict(id) do update set role=excluded.role;
insert into provider_profiles(id,user_id,provider_type,full_name,identity_source) values('${id(12)}','${id(2)}','LAB','Lab fixture','DEMO');
insert into facilities(id,owner_user_id,name,facility_type,verification_status) values('${id(20)}','${id(2)}','Place A','DIAGNOSTIC_LAB','APPROVED'),('${id(21)}','${id(2)}','Place B','DIAGNOSTIC_LAB','PENDING');`);
const review=(status,key,reason='Reviewed evidence')=>as(1,()=>scalar('select v1_review_provider($1,$2,$3,null,$4)',[id(12),status,reason,id(key)]));
await test('place cannot become approved independently of its provider',async()=>{assert.equal(await scalar('select verification_status from facilities where id=$1',[id(20)]),'PENDING');await assert.rejects(()=>q("update facilities set verification_status='APPROVED' where id=$1",[id(20)]),/provider verification/)});
await test('normal user cannot approve or forge evidence/audit',async()=>{await as(2,()=>assert.rejects(()=>q("select v1_review_provider($1,'APPROVED','Reviewed',null,$2)",[id(12),id(30)]),/Administrator/));await as(2,()=>assert.rejects(()=>q("update provider_profiles set verification_status='APPROVED' where id=$1",[id(12)])));await as(2,()=>assert.rejects(()=>q("delete from verification_reviews")))});
await test('approval requires evidence and failure leaves both states pending',async()=>{await assert.rejects(()=>review('APPROVED',31),/evidence/);assert.equal(await scalar('select verification_status from provider_profiles where id=$1',[id(12)]),'PENDING')});
await test('evidence submission is idempotent, immutable and owner-scoped',async()=>{const submit=()=>as(2,()=>scalar("select v1_submit_document('LICENSE','private-reference-001',null,$1)",[id(32)]));assert.equal(await submit(),await submit());await as(2,()=>assert.rejects(()=>q("select v1_submit_document('LICENSE','changed',null,$1)",[id(32)]),/conflict/));assert.equal((await as(3,()=>q('select * from verification_documents'))).rows.length,0)});
await test('approval synchronizes all owned places and records reviewer exactly once',async()=>{const r=await review('APPROVED',33);assert.equal(await review('APPROVED',33),r);assert.equal(await scalar("select count(*)::int from facilities where verification_status='APPROVED'"),2);assert.equal(await scalar('select reviewer_id from verification_reviews where id=$1',[r]),id(1));assert.equal(await scalar('select registry_verified from provider_profiles where id=$1',[id(12)]),false)});
await test('same request key cannot be repurposed',async()=>{await assert.rejects(()=>review('SUSPENDED',33),/conflict/)});
await test('suspension immediately removes operational provider authorization',async()=>{assert.equal(await as(2,()=>scalar("select is_approved_provider('LAB')")),true);await review('SUSPENDED',34);assert.equal(await as(2,()=>scalar("select is_approved_provider('LAB')")),false);assert.equal(await scalar("select count(*)::int from facilities where verification_status='SUSPENDED'"),2);await assert.rejects(()=>review('APPROVED',35),/re-review/)});
await test('restore requires pending review, revocation persists on provider and places',async()=>{await review('PENDING',36);await review('APPROVED',37);await review('REVOKED',38);assert.equal(await scalar("select count(*)::int from facilities where verification_status='REVOKED'"),2);await assert.rejects(()=>review('APPROVED',39),/re-review/)});
await test('demo identity never acquires registry verification from administrative approval',async()=>{await assert.rejects(()=>q('update provider_profiles set registry_verified=true where id=$1',[id(12)]),/Demo identity/);await assert.rejects(()=>q("update facilities set identity_source='DEMO',registry_verified=true where id=$1",[id(20)]),/Demo identity/)});
await test('validation error rolls back synchronized updates and audit',async()=>{await review('PENDING',40);await as(1,()=>assert.rejects(()=>q("select v1_review_provider($1,'APPROVED','Reviewed',$2,$3)",[id(12),'x'.repeat(4001),id(41)])));assert.equal(await scalar('select verification_status from provider_profiles where id=$1',[id(12)]),'PENDING');assert.equal(await scalar("select count(*)::int from facilities where verification_status='PENDING'"),2);assert.equal(await scalar('select count(*)::int from verification_reviews where request_key=$1',[id(41)]),0)});
await test('verification queue is bounded and governance-only',async()=>{await as(2,()=>assert.rejects(()=>q('select * from v1_verification_queue()'),/Administrator/));const rows=(await as(1,()=>q('select * from v1_verification_queue()'))).rows;assert.equal(rows.length,1);assert.equal(Number(rows[0].submitted_documents),1);await as(1,()=>assert.rejects(()=>q("select * from v1_verification_queue('PENDING',-1)"),/Invalid/))});
console.log(`${passed} verification tests passed`);await db.close();


