-- 042: episode-specific operational Care Twin and explicit unverified external completion claims.
begin;
create table external_care_claims(id uuid primary key default gen_random_uuid(),gap_id uuid not null references care_gaps(id),patient_id uuid not null references patient_profiles(id),record_id uuid not null references health_records(id),note text not null,reported_by uuid not null references auth.users(id),request_key uuid not null unique,created_at timestamptz not null default now());
alter table external_care_claims enable row level security;revoke all on external_care_claims from public,anon,authenticated;
create function t2_external_completion(p_gap uuid,p_record uuid,p_note text,p_request uuid) returns uuid language plpgsql security definer set search_path=public as $$
declare g care_gaps;h health_records;r external_care_claims;rid uuid;
begin
 select * into g from care_gaps where id=p_gap for update;select * into h from health_records where id=p_record for share;
 if g.id is null or h.id is null or h.patient_id<>g.patient_id or g.status<>'OPEN' or not c3_gap_actor(g.id) or not a1_has_consent(g.patient_id,'DOCUMENTS','TREATMENT',coalesce(h.record_date::timestamptz,h.created_at)) or p_note is null or length(trim(p_note)) not between 10 and 2000 or p_request is null then raise exception 'Authorized open care gap and patient source document required';end if;
 select * into r from external_care_claims where request_key=p_request;
 if found then if (r.gap_id,r.record_id,r.note,r.reported_by) is distinct from (g.id,h.id,trim(p_note),auth.uid()) then raise exception 'External evidence request conflict';end if;return r.id;end if;
 insert into external_care_claims(gap_id,patient_id,record_id,note,reported_by,request_key) values(g.id,g.patient_id,h.id,trim(p_note),auth.uid(),p_request) returning id into rid;
 update care_gaps set blocked_reason='EXTERNAL_COMPLETION_POSSIBLE_VERIFICATION_PENDING' where id=g.id;
 insert into care_events(patient_id,event_type,source_table,source_id,actor_user_id,metadata) values(g.patient_id,'EXTERNAL_COMPLETION_REPORTED_UNVERIFIED','external_care_claims',rid,auth.uid(),jsonb_build_object('gap_id',g.id,'record_id',h.id));return rid;
end $$;
create function t2_fresh(p_row jsonb,p_time timestamptz,p_open boolean,p_max_age interval default interval '7 days') returns jsonb language sql stable set search_path=public as $$select p_row||jsonb_build_object('source_updated_at',p_time,'freshness',case when p_time is null then 'UNKNOWN' when not p_open then 'HISTORICAL_SOURCE' when p_time<now()-p_max_age then 'STATUS_UNKNOWN_CONFIRMATION_REQUIRED' else 'RECENTLY_RECORDED' end,'freshness_policy_seconds',extract(epoch from p_max_age))$$;
create function t2_twin(p_episode uuid,p_purpose text default 'TREATMENT') returns jsonb language plpgsql security definer set search_path=public as $$
declare e care_episodes;ctx jsonb;nodes jsonb;gaps jsonb;result jsonb;
begin
 select * into e from care_episodes where id=p_episode;if not found then raise exception 'Episode unavailable';end if;
 ctx:=a1_authorized_context(e.patient_id,p_purpose,0);
 if not a1_has_consent(e.patient_id,'ENCOUNTERS',p_purpose,e.source_at) then raise exception 'Episode encounter consent required';end if;
 select coalesce(jsonb_agg(t2_fresh(to_jsonb(n),n.updated_at,n.state not in ('COMPLETED','CANCELLED'))),'[]') into nodes from (
 select n.id,n.kind,n.category,n.state,n.required,n.responsible_role,n.source_kind,n.source_id,n.occurred_at,n.updated_at,n.due_at,n.proof_kind,n.proof_id,
 not exists(select 1 from care_dependencies d join care_nodes p on p.id=d.requires_node_id where d.node_id=n.id and p.state<>'COMPLETED') and n.state not in ('COMPLETED','CANCELLED') ready
 from care_nodes n where n.episode_id=e.id and a1_has_consent(e.patient_id,n.category,p_purpose,coalesce(n.occurred_at,e.source_at)) order by n.due_at nulls last,n.id limit 100)n;
 select coalesce(jsonb_agg(t2_fresh(to_jsonb(g),coalesce(g.closed_at,g.risk_recorded_at,g.created_at),g.status='OPEN')),'[]') into gaps from (
 select g.id,g.graph_node_id,g.gap_type,g.status,g.due_at,g.severity,g.blocked_reason,g.closure_outcome,g.created_at,g.closed_at,g.risk_recorded_at from care_gaps g join care_nodes n on n.id=g.graph_node_id where n.episode_id=e.id and a1_has_consent(e.patient_id,'TIMELINE',p_purpose,g.created_at) and a1_has_consent(e.patient_id,n.category,p_purpose,coalesce(n.occurred_at,e.source_at)) order by g.created_at desc,g.id limit 100)g;
 result:=jsonb_build_object('episode',jsonb_build_object('id',e.id,'patient_id',e.patient_id,'encounter_id',e.encounter_id,'status',e.status,'closure_outcome',e.closure_outcome,'source_at',e.source_at,'closed_at',e.closed_at),'nodes',nodes,'care_gaps',gaps,
 'next_steps',coalesce((select jsonb_agg(x) from jsonb_array_elements(nodes)x where x->>'ready'='true'),'[]'),
 'pathways',coalesce((select jsonb_agg(jsonb_build_object('activation_id',a.id,'version_id',a.version_id,'activated_at',a.activated_at,'definition_state',v.status)) from episode_pathways a join care_pathway_versions v on v.id=a.version_id where a.episode_id=e.id),'[]'),
 'appointments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'scheduled_at',a.scheduled_at,'mode',a.mode,'status',a.status)) from appointments a join encounters c on c.appointment_id=a.id where c.id=e.encounter_id),'[]'),
 'diagnostics',coalesce((select jsonb_agg(t2_fresh(to_jsonb(x),x.updated_at,x.status not in ('COMPLETED','CANCELLED'))) from (select o.id,o.test_name,o.workflow_kind,o.status,o.routing_status,o.ordered_at,greatest(o.ordered_at,(select max(recorded_at) from clinical_source_versions where source_kind='lab_orders' and source_id=o.id),(select max(updated_at) from lab_specimens where lab_order_id=o.id),(select max(updated_at) from diagnostic_studies where lab_order_id=o.id),(select max(greatest(verified_at,doctor_reviewed_at)) from lab_results where lab_order_id=o.id)) updated_at,
 (select jsonb_agg(jsonb_build_object('id',s.id,'status',s.status,'updated_at',s.updated_at,'processing_lab_provider_id',s.processing_lab_provider_id,'collection_centre_id',s.collection_centre_id)) from lab_specimens s where s.lab_order_id=o.id) specimens,
 (select jsonb_build_object('id',s.id,'state',s.state,'updated_at',s.updated_at,'facility_id',s.facility_id) from diagnostic_studies s where s.lab_order_id=o.id) study,
 (select jsonb_build_object('id',r.id,'status',r.status,'verified_at',r.verified_at,'doctor_reviewed_at',r.doctor_reviewed_at,'pending_review',r.doctor_reviewed_at is null) from lab_results r where r.lab_order_id=o.id and r.status='COMPLETED' and r.verified_at is not null and r.report_storage_path is not null) result
 from lab_orders o where o.encounter_id=e.encounter_id and a1_has_consent(e.patient_id,'DIAGNOSTICS',p_purpose,o.ordered_at) order by o.ordered_at desc,o.id limit 50)x),'[]'),
 'prescriptions',coalesce((select jsonb_agg(to_jsonb(x)) from (select p.id,p.status,p.issued_at,(select jsonb_build_object('id',f.id,'status',f.status,'requested_at',f.requested_at,'completed_at',f.completed_at) from prescription_fulfilments f where f.prescription_id=p.id) fulfilment,
 (select jsonb_build_object('id',d.id,'state',d.state,'mode',d.mode,'updated_at',d.updated_at,'received_at',d.received_at) from pharmacy_deliveries d join prescription_fulfilments f on f.id=d.fulfilment_id where f.prescription_id=p.id) receipt
 from prescriptions p where p.encounter_id=e.encounter_id and a1_has_consent(e.patient_id,'PRESCRIPTIONS',p_purpose,p.issued_at) order by p.issued_at desc,p.id limit 50)x),'[]'),
 'referrals',coalesce((select jsonb_agg(t2_fresh(to_jsonb(x),x.updated_at,x.state not in ('CLOSED','CANCELLED','REJECTED'))) from (select id,state,urgency,destination_facility_id,created_at,updated_at from care_referrals where episode_id=e.id and a1_has_consent(e.patient_id,'TIMELINE',p_purpose,created_at) order by created_at desc,id limit 50)x),'[]'),
 'follow_ups',coalesce((select jsonb_agg(t2_fresh(to_jsonb(x),x.updated_at,x.status<>'COMPLETED')) from (select t.id,t.status,t.updated_at,t.verified_at,t.sync_version,(select count(*) from worker_assistance_records a where a.task_id=t.id) assistance_observation_count from follow_up_tasks t join care_gaps g on g.id=t.care_gap_id join care_nodes n on n.id=g.graph_node_id where n.episode_id=e.id and a1_has_consent(e.patient_id,'FOLLOW_UPS',p_purpose,t.assigned_at) order by t.updated_at desc,t.id limit 50)x),'[]'),
 'payer_cases',coalesce((select jsonb_agg(t2_fresh(to_jsonb(x),x.updated_at,x.state not in ('SETTLED','DENIED'))) from (select c.id,c.kind,c.state,c.updated_at,c.submission_version from payer_cases c join facility_invoices i on i.id=c.invoice_id where c.patient_id=e.patient_id and ((i.source_kind='APPOINTMENT' and i.source_id=(select appointment_id from encounters where id=e.encounter_id)) or (i.source_kind='ADMISSION' and exists(select 1 from hospital_admissions h where h.id=i.source_id and h.encounter_id=e.encounter_id))) and a1_has_consent(e.patient_id,'TIMELINE',p_purpose,c.created_at) order by c.created_at desc,c.id limit 50)x),'[]'),
 'emergencies',coalesce((select jsonb_agg(t2_fresh(to_jsonb(x),x.created_at,x.state<>'CLOSED',interval '15 minutes')) from (select id,state,transport_state,accepted_facility_id,created_at from emergency_requests where episode_id=e.id and a1_has_consent(e.patient_id,'TIMELINE',p_purpose,created_at) order by created_at desc,id limit 30)x),'[]'),
 'critical_results',coalesce((select jsonb_agg(t2_fresh(to_jsonb(x),coalesce(x.closed_at,x.acknowledged_at,x.detected_at),x.state not in ('ACKNOWLEDGED','CLOSED'),interval '15 minutes')) from (select c.id,c.state,c.detected_at,c.acknowledged_at,c.closed_at,c.result_id from critical_results c join lab_results r on r.id=c.result_id join lab_orders o on o.id=r.lab_order_id where o.encounter_id=e.encounter_id and a1_has_consent(e.patient_id,'DIAGNOSTICS',p_purpose,o.ordered_at) order by c.detected_at desc,c.id limit 30)x),'[]'),
 'external_claims',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'gap_id',c.gap_id,'record_id',c.record_id,'reported_at',c.created_at,'state',case when n.state='COMPLETED' and n.proof_id is not null then 'OPERATIONAL_SOURCE_COMPLETED_SEPARATELY' else 'EXTERNAL_COMPLETION_POSSIBLE_VERIFICATION_PENDING' end)) from external_care_claims c join care_gaps g on g.id=c.gap_id join care_nodes n on n.id=g.graph_node_id join health_records h on h.id=c.record_id where n.episode_id=e.id and a1_has_consent(e.patient_id,'DOCUMENTS',p_purpose,coalesce(h.record_date::timestamptz,h.created_at)) and a1_has_consent(e.patient_id,'TIMELINE',p_purpose,g.created_at)),'[]'),
 'as_of',now(),'provenance','CURRENT_AUTHORIZED_SOURCE_PROJECTION','scope','One episode; bounded domain lists. Source IDs remain authoritative.','notice','Operational care state, not disease simulation or diagnosis. Missing evidence remains unknown; external claims do not close care.');
 insert into consent_audit(patient_id,actor_user_id,action,purpose) values(e.patient_id,auth.uid(),'CARE_TWIN_READ',p_purpose);return result;
end $$;
-- A cancelled prerequisite cannot silently satisfy proof requirements.
create or replace function g1_next_steps(p_episode uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare graph jsonb;result jsonb;begin
 graph:=g1_episode(p_episode);
 select coalesce(jsonb_agg(x order by (x->>'due_at')::timestamptz nulls last,x->>'id'),'[]') into result from jsonb_array_elements(graph->'nodes')x where x->>'state' not in ('COMPLETED','CANCELLED') and not exists(select 1 from care_dependencies d join care_nodes p on p.id=d.requires_node_id where d.node_id=(x->>'id')::uuid and p.state<>'COMPLETED');
 return jsonb_build_object('episode_id',p_episode,'steps',result,'scope','Persisted evidence-completed prerequisites; not clinical advice');
end $$;
revoke all on function t2_external_completion(uuid,uuid,text,uuid),t2_fresh(jsonb,timestamptz,boolean,interval),t2_twin(uuid,text) from public,anon,authenticated;
grant execute on function t2_external_completion(uuid,uuid,text,uuid),t2_twin(uuid,text) to authenticated;
commit;
