-- 043: fixed-month, minimum-cell-size operational aggregates. No patient rows/identifiers returned.
begin;
create function t3_pulse(p_state text,p_district text,p_month date,p_facility uuid default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare start_at timestamptz;end_at timestamptz;metrics jsonb;cohort_count integer;
begin
 if auth.uid() is null or not (is_admin() or (p_facility is not null and h1_staff(p_facility,array['MANAGER']))) then raise exception 'Aggregate governance or own facility manager required';end if;
 if p_state is null or length(trim(p_state)) not between 1 and 100 or p_district is null or length(trim(p_district)) not between 1 and 100 or p_month is null or p_month<>date_trunc('month',p_month)::date or p_month>=date_trunc('month',now() at time zone 'Asia/Kolkata')::date or p_month<(date_trunc('month',now() at time zone 'Asia/Kolkata')-interval '24 months')::date then raise exception 'Completed calendar month within two years and explicit sourced geography required';end if;
 start_at:=p_month::timestamp at time zone 'Asia/Kolkata';end_at:=(p_month+interval '1 month') at time zone 'Asia/Kolkata';
 with scoped_appointments as materialized (
 select a.id,a.patient_id from appointments a join provider_practices p on p.id=a.practice_id where lower(p.state)=lower(trim(p_state)) and lower(p.district)=lower(trim(p_district)) and (p_facility is null or p.facility_id=p_facility) and a.scheduled_at>=start_at and a.scheduled_at<end_at
 ), cohort as materialized (select distinct patient_id from scoped_appointments), scoped_encounters as materialized (select e.id from encounters e join scoped_appointments a on a.id=e.appointment_id), scoped_nodes as materialized (select n.id from care_nodes n join care_episodes e on e.id=n.episode_id where e.encounter_id in (select id from scoped_encounters)), scored as (
 select c.patient_id,
 exists(select 1 from care_gaps g where g.graph_node_id in (select id from scoped_nodes) and g.patient_id=c.patient_id and g.created_at>=start_at and g.created_at<end_at and g.status='OPEN') open_gap,
 exists(select 1 from care_gaps g join care_nodes n on n.id=g.graph_node_id where g.graph_node_id in (select id from scoped_nodes) and g.patient_id=c.patient_id and g.created_at>=start_at and g.created_at<end_at and n.category='DIAGNOSTICS' and g.status='OPEN' and g.due_at<now()) delayed_diagnostic,
 exists(select 1 from lab_orders o join lab_results r on r.lab_order_id=o.id where o.encounter_id in (select id from scoped_encounters) and o.patient_id=c.patient_id and o.ordered_at>=start_at and o.ordered_at<end_at and r.status='COMPLETED' and r.verified_at is not null and r.doctor_reviewed_at is null) pending_report_review,
 exists(select 1 from follow_up_tasks t where t.care_gap_id in (select id from care_gaps where graph_node_id in (select id from scoped_nodes)) and t.patient_id=c.patient_id and t.assigned_at>=start_at and t.assigned_at<end_at and t.status='COMPLETED' and t.verified_at is not null) followup_completed,
 exists(select 1 from prescriptions p join prescription_fulfilments f on f.prescription_id=p.id where p.encounter_id in (select id from scoped_encounters) and p.patient_id=c.patient_id and p.issued_at>=start_at and p.issued_at<end_at and f.status='DISPENSED') medicines_dispensed,
 exists(select 1 from care_referrals r join care_nodes n on n.source_kind='care_referrals' and n.source_id=r.id where n.id in (select id from scoped_nodes) and r.patient_id=c.patient_id and r.created_at>=start_at and r.created_at<end_at and r.state not in ('CLOSED','REJECTED','CANCELLED') and n.due_at<now()) delayed_referral,
 exists(select 1 from care_episodes e where e.encounter_id in (select id from scoped_encounters) and e.patient_id=c.patient_id and e.source_at>=start_at and e.source_at<end_at and e.status='COMPLETED' and e.closure_outcome='COMPLETED') episode_completed,
 exists(select 1 from care_gaps g where g.graph_node_id in (select id from scoped_nodes) and g.patient_id=c.patient_id and g.created_at>=start_at and g.created_at<end_at and g.status='OPEN' and g.stale_operational_data) stale_context,
 exists(select 1 from critical_results r where r.result_id in (select lr.id from lab_results lr join lab_orders lo on lo.id=lr.lab_order_id where lo.encounter_id in (select id from scoped_encounters)) and r.patient_id=c.patient_id and r.detected_at>=start_at and r.detected_at<end_at and r.state not in ('ACKNOWLEDGED','CLOSED')) critical_ack_pending,
 exists(select 1 from reception_queue q where q.appointment_id in (select id from scoped_appointments) and q.patient_id=c.patient_id and q.checked_in_at>=start_at and q.checked_in_at<end_at and q.state not in ('COMPLETED','CANCELLED')) queue_pending
 from cohort c
 ), counts as (
 select count(*)::integer denominator,count(*) filter(where open_gap)::integer open_gap,count(*) filter(where delayed_diagnostic)::integer delayed_diagnostic,count(*) filter(where pending_report_review)::integer pending_report_review,count(*) filter(where followup_completed)::integer followup_completed,count(*) filter(where medicines_dispensed)::integer medicines_dispensed,count(*) filter(where delayed_referral)::integer delayed_referral,count(*) filter(where episode_completed)::integer episode_completed,count(*) filter(where stale_context)::integer stale_context,count(*) filter(where critical_ack_pending)::integer critical_ack_pending,count(*) filter(where queue_pending)::integer queue_pending from scored
 ), cells as (
 select c.denominator,m.metric,m.numerator from counts c cross join lateral(values('OPEN_CAREGAPS',c.open_gap),('OVERDUE_DIAGNOSTIC_GAPS',c.delayed_diagnostic),('PENDING_REPORT_REVIEWS',c.pending_report_review),('VERIFIED_FOLLOWUP_COMPLETION',c.followup_completed),('MEDICINES_DISPENSED',c.medicines_dispensed),('OVERDUE_REFERRAL_GAPS',c.delayed_referral),('EPISODE_COMPLETION_WITHOUT_EXCEPTIONS',c.episode_completed),('CLINICIAN_FLAGGED_STALE_CONTEXT',c.stale_context),('CRITICAL_ACKNOWLEDGEMENT_PENDING',c.critical_ack_pending),('UNFINISHED_QUEUE',c.queue_pending))m(metric,numerator)
 ) select jsonb_agg(jsonb_build_object('metric',metric,'numerator',case when denominator>=20 and numerator>=10 and denominator-numerator>=10 then numerator end,'denominator',case when denominator>=20 and numerator>=10 and denominator-numerator>=10 then denominator end,'suppression_state',case when denominator>=20 and numerator>=10 and denominator-numerator>=10 then 'RELEASED' else 'SUPPRESSED_MINIMUM_CELL_SIZE' end) order by metric) into metrics from cells;
 insert into audit_logs(actor_user_id,action,entity_type,entity_id,metadata) values(auth.uid(),'AGGREGATE_PULSE_READ','aggregate_scope',coalesce(p_facility::text,'DISTRICT'),jsonb_build_object('state',p_state,'district',p_district,'month',p_month));
 return jsonb_build_object('scope',jsonb_build_object('state',trim(p_state),'district',trim(p_district),'facility_id',p_facility),'window_start',start_at,'window_end_exclusive',end_at,'last_refreshed',now(),'data_freshness','CURRENT_RECORDED_STATE_OF_FIXED_MONTH_COHORT','minimum_cell_size',10,'metrics',metrics,'provenance','Appointments linked to practices with explicitly stored state/district; unmapped records excluded. Numerators count distinct members of the appointment cohort, not events. Current source state, not retrospective end-of-month state.','limitations','Small numerator and complementary cells are suppressed. No arbitrary date windows or patient filters. This is not a formal differential-privacy guarantee. Stock/capability geography aggregates require verified source mappings.');
end $$;
revoke all on function t3_pulse(text,text,date,uuid) from public,anon,authenticated;
grant execute on function t3_pulse(text,text,date,uuid) to authenticated;
commit;
