import assert from 'node:assert/strict';
import {orchestrateCare} from '../supabase/functions/_shared/ai-orchestrator.mjs';
import {governedConfig} from '../supabase/functions/_shared/model-router.mjs';
const context={patient_id:'p',actor_role:'PATIENT',encounters:[{id:'e',started_at:'2020-01-01',clinical_notes:'Original clinician note'}]};
const config={provider:'own-model',url:'https://fixture.invalid/select',key:'fixture-only',model:'fixture-v1'};
const run=(extra={})=>orchestrateCare({patientId:'p',question:'History dikhao',language:'Hinglish',config,retrieve:async()=>context,transport:async()=>new Response(JSON.stringify({outcome:'SOURCES_FOUND',selected_source_ids:['e']})),...extra});
let n=0;async function test(name,fn){await fn();n++;console.log('PASS '+name)}
await test('owned serving contract uses authorized sources and forbids retention/training',async()=>{const r=await run({transport:async(url,init)=>{const b=JSON.parse(init.body);assert.equal(b.constraints.no_training,true);assert.equal(b.constraints.no_retention,true);assert.equal(b.request.role,'PATIENT');assert.equal(b.model_version,'fixture-v1');return new Response(JSON.stringify({outcome:'SOURCES_FOUND',selected_source_ids:['e'],answer:'Invented diagnosis'}))}});assert.match(r.answer.text,/Original clinician note/);assert.doesNotMatch(r.answer.text,/Invented diagnosis/);assert.equal(r.answer.language,'Hinglish');assert.deepEqual(r.answer.citations,[{source_id:'e',date:'2020-01-01'}])});
await test('auto language chooses Hindi narration while preserving original source text',async()=>{const r=await run({question:'इतिहास',language:'Auto'});assert.equal(r.answer.language,'Hindi');assert.match(r.answer.text,/दिनांकित/);assert.match(r.answer.text,/Original clinician note/)});
await test('unknown owned-model citations and unsupported output facts fail closed',async()=>{await assert.rejects(()=>run({transport:async()=>new Response(JSON.stringify({outcome:'SOURCES_FOUND',selected_source_ids:['wrong']}))}),/SOURCE_REFERENCE/);await assert.rejects(()=>run({transport:async()=>new Response(JSON.stringify({outcome:'UNSUPPORTED_REQUEST',selected_source_ids:['e']}))}),/INVALID_MODEL/)});
await test('route resolution happens after authorization and is rechecked after model latency',async()=>{let calls=0;await assert.rejects(()=>run({config:async()=>{calls++;return config},retrieve:async()=>{throw Error('DENIED')}}),/DENIED/);assert.equal(calls,0);await assert.rejects(()=>run({config:async()=>({...config,model_version_id:'m',route_revision:++calls})}),/MODEL_ROUTE_CHANGED/)});
await test('governed router uses only server configuration references and never silently falls back',async()=>{const env={FIXTURE_KEY:'fixture-only',FIXTURE_URL:'https://fixture.invalid'};const r=await governedConfig({language:'English',environment:k=>env[k],route:async()=>({revision:3,primary:{id:'m',version:'v1',provider_kind:'OWN_MODEL',config_ref:'FIXTURE',capabilities:['SOURCE_SELECTION'],languages:['English']},fallback:{id:'external'}})});assert.equal(r.provider,'own-model');assert.equal(r.route_revision,3);assert.equal(r.fallback,undefined)});
console.log(`${n} model router tests passed`);
