import assert from 'node:assert/strict';
import {sourceRecords,groundSelection,selectWithProvider} from '../supabase/functions/swasthya-snapshot/grounding.mjs';
const base={encounters:[{id:'source-a',started_at:'2026-01-01',chief_complaint:'Fixture complaint',clinical_notes:'Source note',status:'COMPLETED'}]};
let n=0;async function test(name,fn){await fn();n++;console.log('PASS '+name)}
await test('new source history changes snapshot source text',()=>{const before=sourceRecords(base);const after=sourceRecords({...base,encounters:[{...base.encounters[0],clinical_notes:'New recorded source history'}]});assert.notEqual(before[0].text,after[0].text);assert.match(after[0].text,/New recorded source history/)});
await test('missing information is unknown and zero values are retained',()=>{const r=sourceRecords({...base,prescriptions:[{id:'rx',issued_at:'2026-01-01',items:[{medicine_name:'Fixture',quantity_prescribed:0}]}]});assert.match(r[0].text,/Recorded diagnosis: Not documented/);assert.match(r[1].text,/total units prescribed: 0/)});
await test('model text cannot change clinical source facts',()=>{const r=sourceRecords(base);const output=groundSelection(r,{selected_source_ids:['source-a'],text:'Invented diagnosis and dose'});assert.deepEqual(output,[r[0]]);assert.doesNotMatch(JSON.stringify(output),/Invented/)});
await test('unknown duplicate empty and excessive citations rejected',()=>{const r=sourceRecords(base);for(const ids of [['fabricated'],['source-a','source-a'],[],Array(13).fill('source-a')])assert.throws(()=>groundSelection(r,{selected_source_ids:ids}))});
await test('unverified results excluded; uploaded metadata never becomes clinical evidence',()=>{const r=sourceRecords({diagnostics:[{id:'order',ordered_at:'2026-01-01',result:{id:'draft',status:'DRAFT',result_json:{value:999}}}],health_records:[{id:'file',created_at:'2026-01-01',original_filename:'record.pdf'}]});assert.equal(r.some(x=>x.source_id==='draft'),false);assert.match(r[1].text,/contents have not been extracted/)});
await test('no credentials means no fabricated snapshot and no provider call',()=>assert.rejects(()=>selectWithProvider(sourceRecords(base),{},()=>{throw Error('should not call')}),/CONFIGURATION_REQUIRED/));
await test('provider boundary submits actual sources and validates response',async()=>{const r=sourceRecords(base);const result=await selectWithProvider(r,{url:'https://fixture.invalid',key:'fixture-secret'},async(url,init)=>{const body=JSON.parse(init.body);assert.deepEqual(body.records.map(x=>x.source_id),r.map(x=>x.source_id));assert.notDeepEqual(body.records,r);assert.ok(body.records.every(x=>!x.text.includes('Clinician notes')));assert.equal(init.redirect,'error');return new Response(JSON.stringify({selected_source_ids:['source-a']}))});assert.deepEqual(result,r)});
await test('oversized context and insecure provider endpoint rejected',async()=>{assert.throws(()=>sourceRecords({encounters:[{...base.encounters[0],clinical_notes:'x'.repeat(180001)}]}),/CONTEXT_TOO_LARGE/);await assert.rejects(()=>selectWithProvider(sourceRecords(base),{url:'http://fixture.invalid',key:'x'}),/INVALID_PROVIDER_CONFIGURATION/)});
console.log(`${n} snapshot grounding tests passed`);
